import type { StudyGuide } from '@/types/studyGuide'

// Pesos: preguntas MIR 2015-2025 agrupadas en 17 bloques temáticos propios + clasificación propia del MIR 2026
// (cuaderno oficial, versión 0). Respuestas del 2026 contrastadas con las definitivas publicadas tras las impugnaciones.
export const CIRUGIA_GENERAL_GUIDE: StudyGuide = {
  subjectId: 'cirugia-general',
  title: 'Digestivo y Cirugía General',
  subtitle: 'Qué estudiar, en qué orden y cuánto pesa cada cosa en el MIR',
  targetExam: 'MIR 2027',
  lastExam: 'MIR 2026',
  historyRange: '2015–2025',
  perYear: [
    { year: 2015, count: 22 },
    { year: 2016, count: 28 },
    { year: 2017, count: 26 },
    { year: 2018, count: 22 },
    { year: 2019, count: 24 },
    { year: 2020, count: 20 },
    { year: 2021, count: 15 },
    { year: 2022, count: 18 },
    { year: 2023, count: 14 },
    { year: 2024, count: 23 },
    { year: 2025, count: 22 },
    { year: 2026, count: 26 },
  ],
  lastExamTotal: 26,
  lastExamReserveTotal: 2,
  topics: [
    {
      id: 'esofago',
      code: 'ESO',
      name: 'Esófago: ERGE, esofagitis, motilidad y cáncer',
      shortName: 'Esófago',
      tier: 'imprescindible',
      perYear: [1, 2, 1, 3, 2, 2, 1, 3, 3, 1, 2, 3],
      lastExamReserve: 0,
      pages: 18,
      focus:
        'El bloque más constante de la asignatura: no ha faltado ningún año (de 1 a 3 preguntas). En 2026, Barrett con displasia, esofagitis grado C y Zenker.',
      hotspots: [
        { name: 'ERGE y esófago de Barrett: vigilancia y tratamiento de la displasia', heat: 3 },
        { name: 'Esofagitis eosinofílica (anillos, >15 eosinófilos/campo)', heat: 3 },
        { name: 'Acalasia y manometría de alta resolución', heat: 2 },
        { name: 'Divertículos (Zenker), hernia de hiato, lesiones benignas', heat: 2 },
        { name: 'Esofagitis infecciosas y por cáusticos', heat: 1 },
        { name: 'Cáncer de esófago', heat: 1 },
      ],
      keys: [
        'ERGE típica sin alarma: IBP empírico sin endoscopia. Se hace gastroscopia si hay disfagia, sangrado, anemia, pérdida de peso o mala respuesta. Los síntomas no predicen cuánta lesión hay.',
        'Esofagitis grave (Los Ángeles C o D): IBP a dosis plena 8 semanas, mantenimiento indefinido y endoscopia de control, porque la inflamación puede tapar un Barrett.',
        'Barrett = epitelio columnar con metaplasia intestinal (células caliciformes). Sin displasia: endoscopia cada 3-5 años. Displasia de bajo grado confirmada por un segundo patólogo: ablación por radiofrecuencia. Alto grado o lesión visible: resección endoscópica y luego ablación. La esofaguectomía no es para la displasia.',
        'Esofagitis eosinofílica: joven atópico con disfagia o impactación alimentaria; anillos y surcos en la endoscopia; biopsias con ≥15 eosinófilos por campo. Tratamiento: IBP, budesonida deglutida o dieta de eliminación; dupilumab en refractarios.',
        'Acalasia: disfagia a sólidos y líquidos desde el principio; manometría con relajación incompleta del EEI y aperistalsis. Tratamiento: dilatación, miotomía de Heller o POEM. Descartar pseudoacalasia tumoral en ancianos.',
        'Zenker: divertículo de pulsión por la pared posterior (triángulo de Killian), ancianos, halitosis y regurgitación de comida sin digerir. Diagnóstico con bario; tratamiento, miotomía del cricofaríngeo.',
        'Cáncer: epidermoide (tercio medio, tabaco y alcohol, cáusticos, acalasia) frente a adenocarcinoma (tercio distal, Barrett, obesidad). Localmente avanzado: neoadyuvancia y esofaguectomía.',
      ],
      trap: 'Ante un paciente con disfagia, lo primero es distinguir si es orofaríngea (le cuesta iniciar la deglución, tose, regurgita por la nariz) o esofágica (nota que se le queda el alimento retroesternal). El estudio es distinto en cada caso.',
    },
    {
      id: 'ccr',
      code: 'CCR',
      name: 'Tumores del intestino delgado y grueso',
      shortName: 'Colorrectal',
      tier: 'imprescindible',
      perYear: [2, 3, 1, 2, 2, 1, 1, 0, 0, 5, 4, 2],
      lastExamReserve: 1,
      pages: 12,
      focus:
        'El tema más preguntado de la asignatura desde 2015, con 9 preguntas solo entre 2024 y 2025. Cribado, Lynch, cirugía oncológica y tratamiento según biomarcadores.',
      hotspots: [
        { name: 'Síndrome de Lynch: genes MMR, inestabilidad de microsatélites, cribado', heat: 3 },
        { name: 'Cribado poblacional y de familiares; pólipos y vigilancia', heat: 3 },
        { name: 'Cirugía oncológica: linfadenectomía, escisión del mesorrecto, estadificación del recto por RM', heat: 3 },
        { name: 'Tratamiento sistémico: RAS, lateralidad, MSI-alto, déficit de DPD', heat: 2 },
        { name: 'Pólipo malignizado: cuándo basta la resección endoscópica', heat: 2 },
        { name: 'Poliposis (PAF, Peutz-Jeghers) y tumores de intestino delgado', heat: 1 },
      ],
      keys: [
        'Cribado de riesgo medio: sangre oculta en heces (inmunológica) cada 2 años entre los 50 y los 69 años (programas hasta 74-75). No se recomienda por encima de los 85.',
        'Familiar de primer grado con CCR antes de los 60, o dos familiares de primer grado a cualquier edad: colonoscopia cada 5 años desde los 40 (o 10 años antes del caso más joven). Un solo familiar con 60 años o más: cribado como la población general.',
        'Lynch: autosómico dominante, mutaciones en MLH1, MSH2, MSH6 o PMS2, tumores con inestabilidad de microsatélites. Colonoscopia cada 1-2 años desde los 20-25 años (más tarde en MSH6/PMS2); vigilar además endometrio y ovario.',
        'Pólipo malignizado: si el carcinoma no pasa la muscularis mucosae (intramucoso) basta la polipectomía; si invade la submucosa con factores de riesgo (margen afectado, invasión linfovascular, mal diferenciado, budding) hay que operar.',
        'Colon: resección con márgenes amplios, ligadura del pedículo en su origen y linfadenectomía (al menos 12 ganglios); órganos infiltrados en bloque. Quimioterapia adyuvante en el estadio III y en el II de alto riesgo.',
        'Recto medio e inferior: la RM pélvica decide (T, fascia mesorrectal, ganglios). Localmente avanzado: neoadyuvancia; después escisión total del mesorrecto. Si la respuesta es completa, se puede valorar "esperar y ver".',
        'Metastásico: anti-EGFR (cetuximab, panitumumab) solo con RAS no mutado y mejor en colon izquierdo; MSI-alto → inmunoterapia (pembrolizumab) en primera línea. Antes de las fluoropirimidinas se estudia el déficit de DPD, que dispara su toxicidad.',
      ],
      trap: 'Anemia ferropénica en un varón o en una mujer posmenopáusica = colonoscopia (y gastroscopia) aunque no haya síntomas digestivos.',
    },
    {
      id: 'plastica',
      code: 'PLA',
      name: 'Cirugía plástica',
      shortName: 'Plástica',
      tier: 'imprescindible',
      perYear: [0, 1, 2, 0, 2, 2, 1, 2, 1, 1, 4, 3],
      lastExamReserve: 0,
      pages: 6,
      focus:
        'Solo 6 páginas y 7 preguntas en los dos últimos MIR: el tema con mejor rendimiento por página de la asignatura, y sigue subiendo.',
      hotspots: [
        { name: 'Quemaduras: profundidad, extensión, reposición, grandes quemados', heat: 3 },
        { name: 'Injertos y colgajos; reconstrucción mamaria (DIEP)', heat: 3 },
        { name: 'Linfedema y lipedema', heat: 2 },
        { name: 'Expansión tisular y cicatrización', heat: 1 },
        { name: 'Quemaduras eléctricas y químicas', heat: 1 },
      ],
      keys: [
        'Profundidad: epidérmica (eritema doloroso, sin ampollas); dérmica superficial (ampollas, muy dolorosa, cura en unas 2 semanas sin secuelas); dérmica profunda (blanquecina, menos dolor, más de 3 semanas y cicatriz → injerto); subdérmica (acartonada, indolora → escisión e injerto).',
        'Extensión con la regla de los 9 (palma del paciente ≈ 1 %). Parkland: 4 mL × kg × % de superficie en 24 h, la mitad en las primeras 8 h, con ritmo de diuresis 0,5-1 mL/kg/h. El primer grado no cuenta.',
        'Criterios de unidad de quemados: extensión grande, zonas especiales (cara, manos, pies, genitales, articulaciones), eléctricas y químicas, inhalación, extremos de edad o comorbilidad.',
        'Injerto: tejido sin vasos propios que vive del lecho; no prende sobre hueso sin periostio, tendón sin paratendón ni cartílago sin pericondrio. Colgajo: lleva su pedículo vascular; sirve para lechos pobres.',
        'Reconstrucción mamaria autóloga: el DIEP (perforantes de la epigástrica inferior profunda) es la referencia y tolera la radioterapia mejor que el implante.',
        'Linfedema: Stemmer positivo, a menudo tras linfadenectomía y radioterapia; se trata con terapia descongestiva (drenaje, vendaje, prenda de compresión a medida). El lipedema es grasa simétrica que respeta los pies (Stemmer negativo).',
        'Quemadura eléctrica: el daño interno supera al de la piel; vigilar arritmias, rabdomiólisis y síndrome compartimental.',
      ],
      trap: 'En un quemado lo que más mata en un incendio doméstico no es la piel sino el humo: intoxicación por CO (y por cianuro). Oxígeno al 100 % desde el primer momento.',
    },
    {
      id: 'eii',
      code: 'EII',
      name: 'Enfermedad inflamatoria intestinal y colon irritable',
      shortName: 'EII',
      tier: 'imprescindible',
      perYear: [1, 2, 1, 2, 0, 2, 1, 1, 1, 1, 1, 3],
      lastExamReserve: 0,
      pages: 12,
      focus:
        'Cae casi todos los años y en 2026 subió a 3: diagnóstico diferencial CU/Crohn, cirugía urgente del megacolon y vigilancia del cáncer.',
      hotspots: [
        { name: 'Diferencias entre colitis ulcerosa y enfermedad de Crohn', heat: 3 },
        { name: 'Brote grave de CU y megacolon tóxico: tratamiento médico y cirugía', heat: 3 },
        { name: 'Vigilancia del cáncer colorrectal en la EII', heat: 3 },
        { name: 'Biológicos: mecanismo, cribado previo y efectos adversos', heat: 2 },
        { name: 'Manifestaciones extraintestinales y enfermedad perianal', heat: 2 },
        { name: 'Colon irritable: criterios de Roma IV', heat: 1 },
      ],
      keys: [
        'CU: continua desde el recto, solo mucosa, rectorragia; tabaco protector; asocia colangitis esclerosante. Crohn: transmural y parcheado, de boca a ano (íleon terminal típico), fístulas, estenosis, enfermedad perianal y granulomas no caseificantes; el tabaco lo empeora.',
        'Ojo con los absolutos: el recto puede parecer respetado en una CU tratada con tópicos y el íleon puede inflamarse por reflujo en la pancolitis.',
        'Brote grave de CU: ingreso, corticoides IV, profilaxis de TVP y descartar C. difficile y CMV. Sin respuesta al tercer día: infliximab o ciclosporina. Si fracasa, o hay megacolon, perforación o hemorragia masiva: colectomía.',
        'Cirugía urgente de la CU: colectomía total con ileostomía terminal, dejando el recto. La proctocolectomía con reservorio ileoanal es la cirugía electiva y se hace en un segundo tiempo.',
        'Vigilancia del CCR: colitis extensa o izquierda, a partir de los 8 años de síntomas, con cromoendoscopia y biopsias dirigidas; cada 1-5 años según riesgo. Con colangitis esclerosante: anual desde el diagnóstico. La proctitis aislada no se vigila.',
        'Antes de un biológico o inmunosupresor: descartar tuberculosis latente, VHB, VZV y actualizar vacunas. Anti-TNF: infecciones y linfoma; tiopurinas: cáncer de piel no melanoma; vedolizumab (anti-integrina α4β7) es selectivo del intestino.',
        'Manifestaciones que van con la actividad del brote: artritis periférica, eritema nudoso, epiescleritis. Independientes del brote: espondilitis y sacroileítis, uveítis, colangitis esclerosante y pioderma (este, variable).',
      ],
      trap: 'Una fístula perianal compleja en un paciente joven es Crohn mientras no se demuestre lo contrario: se trata la enfermedad de base, no solo la fístula.',
    },
    {
      id: 'biliar',
      code: 'BIL',
      name: 'Vesícula y vía biliar',
      shortName: 'Vía biliar',
      tier: 'imprescindible',
      perYear: [1, 1, 1, 1, 2, 4, 0, 1, 2, 2, 2, 1],
      lastExamReserve: 0,
      pages: 8,
      focus:
        'La patología quirúrgica más preguntada: 1-2 preguntas casi todos los años, con muchas imágenes (ecografía, colangio-RM).',
      hotspots: [
        { name: 'Coledocolitiasis y colangitis aguda: CPRE y colecistectomía', heat: 3 },
        { name: 'Colecistitis aguda y sus complicaciones (gangrenosa, enfisematosa, íleo biliar)', heat: 3 },
        { name: 'Colangiocarcinoma y cáncer de vesícula', heat: 2 },
        { name: 'Pólipos vesiculares y vesícula de porcelana', heat: 2 },
        { name: 'Indicaciones de colecistectomía', heat: 1 },
      ],
      keys: [
        'Colelitiasis asintomática: no se opera (salvo excepciones, como vesícula de porcelana o cálculos mayores de 3 cm). El cólico biliar sí es indicación de colecistectomía programada.',
        'Colecistitis aguda: fiebre, dolor en hipocondrio derecho, Murphy positivo y ecografía con pared engrosada. Tratamiento: antibiótico y colecistectomía laparoscópica precoz. Si el paciente no puede operarse: colecistostomía percutánea.',
        'Coledocolitiasis: ictericia y colestasis tras un cólico. Probabilidad alta → CPRE con esfinterotomía y extracción; intermedia → colangio-RM o ecoendoscopia antes. Siempre colecistectomía después.',
        'Colangitis: tríada de Charcot (fiebre, ictericia, dolor); con shock y confusión es la péntada de Reynolds. Antibiótico y drenaje biliar por CPRE, urgente si es grave.',
        'Íleo biliar: fístula colecistoentérica en una mujer anciana; obstrucción de delgado con aerobilia (tríada de Rigler). Se extrae el cálculo por enterotomía; la fístula se trata después si hace falta.',
        'Pólipos vesiculares: se operan si miden 10 mm o más, crecen o dan síntomas; con 6-9 mm y factores de riesgo (más de 50 años, colangitis esclerosante, pólipo sésil) también se valora.',
        'Colangiocarcinoma: ictericia indolora progresiva; factor de riesgo clásico, la colangitis esclerosante. El perihiliar (Klatskin) es el más frecuente.',
      ],
      trap: 'Ictericia con dolor tipo cólico y sin fiebre = coledocolitiasis; con fiebre = colangitis; sin dolor y progresiva = tumor. Esa es la pregunta del MIR 2026 con la imagen 5.',
    },
    {
      id: 'pancreas-tumores',
      code: 'PAN',
      name: 'Tumores pancreáticos',
      shortName: 'Tumor páncreas',
      tier: 'alta',
      perYear: [1, 3, 0, 2, 2, 0, 2, 1, 2, 1, 0, 2],
      lastExamReserve: 0,
      pages: 6,
      focus:
        'Más de una pregunta al año en solo 6 páginas. Adenocarcinoma (resecabilidad y Whipple) y lesiones quísticas (NMPI).',
      hotspots: [
        { name: 'Adenocarcinoma: clínica, diagnóstico y criterios de resecabilidad', heat: 3 },
        { name: 'NMPI: ducto principal frente a rama secundaria, signos de alarma', heat: 3 },
        { name: 'Duodenopancreatectomía cefálica y sus complicaciones', heat: 2 },
        { name: 'Tumores neuroendocrinos y otros quistes', heat: 1 },
      ],
      keys: [
        'Adenocarcinoma de cabeza: ictericia indolora, pérdida de peso, vesícula palpable (Courvoisier-Terrier) y a veces diabetes reciente. Diagnóstico y estadificación con TC con contraste; CA 19-9 para seguimiento, no para diagnóstico.',
        'Biopsia (PAAF por ecoendoscopia) solo si se va a dar neoadyuvancia o no es resecable; si es claramente resecable, se opera sin confirmación histológica.',
        'Resecable → cirugía (Whipple en la cabeza, pancreatectomía distal en cuerpo y cola) y quimioterapia adyuvante. Borderline → neoadyuvancia. Localmente avanzado o metastásico → quimioterapia; la ictericia se paliará con prótesis biliar por CPRE.',
        'Complicación más frecuente y grave del Whipple: la fístula pancreática. Puede dar colecciones y hemorragia tardía por pseudoaneurisma.',
        'NMPI de ducto principal (dilatado 5-9 mm = alarma; 10 mm o más = alto riesgo): alto potencial maligno → cirugía. De rama secundaria sin alarma: vigilancia con RM. En la endoscopia, la papila que expulsa moco es típica del ducto principal.',
        'Cistoadenoma seroso: benigno, mujer mayor, aspecto en panal con cicatriz central. Mucinoso: mujer de mediana edad, cola, con estroma ovárico; se opera.',
      ],
      trap: 'En las NMPI no se hace pancreatectomía total por sistema: se reseca lo afectado y la total queda para la afectación difusa.',
    },
    {
      id: 'cirrosis',
      code: 'CIR',
      name: 'Cirrosis y sus complicaciones (alcohol, MASLD, otras causas)',
      shortName: 'Cirrosis',
      tier: 'alta',
      perYear: [1, 3, 2, 2, 1, 2, 0, 2, 0, 0, 2, 1],
      lastExamReserve: 1,
      pages: 20,
      focus:
        'Era el tema estrella de Digestivo y ha bajado (de 1,6 a 1,0 preguntas por año), pero en 2025 volvieron dos y en 2026 dos más (una anulada y otra impugnada en reserva).',
      hotspots: [
        { name: 'Hemorragia por varices: tratamiento agudo y profilaxis', heat: 3 },
        { name: 'Ascitis, gradiente albúmina suero-ascitis y PBE', heat: 3 },
        { name: 'Encefalopatía hepática: desencadenantes y tratamiento', heat: 2 },
        { name: 'Pronóstico: Child-Pugh y MELD', heat: 2 },
        { name: 'Colangitis biliar primaria y colangitis esclerosante', heat: 2 },
        { name: 'Hepatitis alcohólica y MASLD', heat: 1 },
      ],
      keys: [
        'Varices sin sangrado: betabloqueante no cardioselectivo (propranolol, carvedilol) o ligadura. Hemorragia aguda: vasoactivo (terlipresina, somatostatina) desde el principio, profilaxis antibiótica (ceftriaxona), transfusión restrictiva (Hb 7-8) y endoscopia con ligadura en menos de 12 h. TIPS precoz en pacientes de alto riesgo.',
        'Gradiente albúmina suero-ascitis de 1,1 g/dL o más = hipertensión portal. Tratamiento: restricción de sal, espironolactona ± furosemida; paracentesis evacuadora con albúmina si es grande o refractaria.',
        'PBE: más de 250 PMN/mm³ en el líquido ascítico. Cefalosporina de 3.ª generación + albúmina (previene el síndrome hepatorrenal). Tras un episodio, profilaxis con norfloxacino indefinida.',
        'Encefalopatía: buscar el desencadenante (infección, hemorragia, estreñimiento, diuréticos e iones, sedantes) y dar lactulosa; rifaximina para prevenir recurrencias. El amonio no se mide de rutina.',
        'Child-Pugh (bilirrubina, albúmina, INR, ascitis, encefalopatía) y MELD (bilirrubina, INR, creatinina, sodio). El MELD ordena la lista de trasplante.',
        'CBP: mujer de mediana edad, prurito, fosfatasa alcalina alta y anticuerpos antimitocondriales → ácido ursodesoxicólico. CEP: varón joven con colitis ulcerosa, colangio-RM "arrosariada", riesgo de colangiocarcinoma, sin tratamiento médico eficaz.',
        'Hepatitis alcohólica: ictericia en bebedor activo, AST/ALT mayor de 2; si la función discriminante de Maddrey es 32 o más, prednisolona. MASLD: la fibrosis (FIB-4, elastografía) marca el pronóstico; tratamiento con pérdida de peso.',
      ],
      trap: 'Hemólisis con acantocitos ("células en espuela") en un cirrótico alcohólico avanzado: es la anemia por acantocitos, de mal pronóstico. Fue la pregunta 13 del 2026 (anulada).',
    },
    {
      id: 'higado-tumores',
      code: 'HCC',
      name: 'Abscesos, tumores hepáticos y trasplante',
      shortName: 'Hepatocarcinoma',
      tier: 'alta',
      perYear: [3, 1, 3, 1, 1, 0, 0, 2, 1, 2, 0, 0],
      lastExamReserve: 0,
      pages: 10,
      focus:
        'Sobre todo hepatocarcinoma: cribado, diagnóstico por imagen y BCLC. En 2025 y 2026 no cayó nada: es de los que pueden volver.',
      hotspots: [
        { name: 'Hepatocarcinoma: cribado, diagnóstico no invasivo, BCLC', heat: 3 },
        { name: 'Trasplante hepático: indicaciones, criterios de Milán, MELD', heat: 2 },
        { name: 'Tumores benignos: hemangioma, HNF, adenoma', heat: 2 },
        { name: 'Absceso hepático piógeno y amebiano', heat: 1 },
      ],
      keys: [
        'Cribado del hepatocarcinoma: ecografía cada 6 meses en cirróticos candidatos a tratamiento (y en algunos portadores de VHB sin cirrosis).',
        'En cirrótico, un nódulo de más de 1 cm con captación arterial y lavado en fase venosa o tardía (TC o RM) es diagnóstico sin biopsia. Si la imagen no es típica, se biopsia.',
        'BCLC: 0-A (único o hasta 3 de ≤3 cm, buen estado) → resección si no hay hipertensión portal, trasplante o ablación. B (multinodular) → quimioembolización. C (invasión vascular o metástasis) → tratamiento sistémico (atezolizumab + bevacizumab en primera línea). D → paliativos.',
        'Criterios de Milán para trasplante: nódulo único de hasta 5 cm, o hasta 3 nódulos de ≤3 cm, sin invasión vascular ni diseminación.',
        'Hemangioma: el tumor benigno más frecuente, captación periférica en glóbulos y relleno centrípeto; no se toca. HNF: cicatriz central, sin riesgo. Adenoma: mujer con anticonceptivos, riesgo de sangrado y malignización; se opera si mide más de 5 cm o en varones.',
        'Absceso piógeno: origen biliar, drenaje percutáneo y antibiótico. Amebiano: joven de zona endémica, lóbulo derecho, metronidazol sin drenaje.',
      ],
      trap: 'El hepatocarcinoma puede aparecer en la MASLD antes de la cirrosis (fibrosis F3); el cribado se centra en los cirróticos, pero la ausencia de cirrosis no lo descarta.',
    },
    {
      id: 'estomago',
      code: 'EST',
      name: 'Estómago: hemorragia digestiva, úlcera, H. pylori y tumores',
      shortName: 'Estómago',
      tier: 'media',
      perYear: [4, 3, 4, 1, 3, 1, 2, 3, 0, 0, 0, 1],
      lastExamReserve: 0,
      pages: 22,
      focus:
        'Fue un bloque fuerte (3-4 preguntas hasta 2017) y ha caído en picado: 0 en 2023, 2024 y 2025. En 2026, una úlcera sangrante por AINE.',
      hotspots: [
        { name: 'Hemorragia digestiva alta: Forrest, Glasgow-Blatchford, endoscopia', heat: 2 },
        { name: 'Úlcera péptica por AINE y por H. pylori', heat: 2 },
        { name: 'H. pylori: diagnóstico y tratamiento erradicador', heat: 2 },
        { name: 'Cáncer gástrico: tipos de Lauren y factores de riesgo', heat: 1 },
        { name: 'Gastroparesia y gastritis crónica', heat: 1 },
      ],
      keys: [
        'Hemorragia digestiva alta: estabilizar, transfusión restrictiva (Hb 7-8), IBP IV y endoscopia en menos de 24 h. Glasgow-Blatchford 0-1: manejo ambulatorio.',
        'Forrest: Ia (a chorro), Ib (babeante), IIa (vaso visible) y IIb (coágulo adherido) → tratamiento endoscópico combinado; IIc (hematina) y III (base limpia) → solo IBP y alta precoz.',
        'Úlcera gástrica: biopsias siempre y endoscopia de control hasta la cicatrización (puede ser un cáncer). La duodenal no necesita control si los síntomas desaparecen.',
        'AINE: suspender si se puede; si no, añadir IBP. El AAS de prevención secundaria se reintroduce pronto con IBP.',
        'H. pylori: test del aliento o antígeno en heces (sin IBP en las 2 semanas previas). Erradicación empírica con cuádruple terapia 10-14 días (bismuto o concomitante) y confirmar la curación.',
        'Cáncer gástrico: tipo intestinal (H. pylori, atrofia, metaplasia) frente a difuso (células en anillo de sello, linitis plástica; CDH1 hereditario).',
        'Gastroparesia: diabético de larga evolución con saciedad precoz y vómitos; gammagrafía de vaciamiento gástrico; procinéticos.',
      ],
      trap: 'Bloque muy extenso para lo que rinde ahora: estúdialo con esquemas, sin perder tiempo en detalles de Zollinger-Ellison o gastritis.',
    },
    {
      id: 'hepatopatias',
      code: 'HEP',
      name: 'Hepatitis y otras hepatopatías (virales, autoinmune, fármacos, metabólicas)',
      shortName: 'Hepatitis',
      tier: 'media',
      perYear: [2, 4, 0, 3, 5, 3, 2, 0, 0, 2, 0, 1],
      lastExamReserve: 0,
      pages: 32,
      focus:
        'Muchas páginas (32) para lo que se pregunta ahora: bajó de 2,7 a 0,6 preguntas al año. Lo más rentable: serología del VHB, hemocromatosis y alfa-1-antitripsina.',
      hotspots: [
        { name: 'Serología de las hepatitis virales, sobre todo VHB', heat: 2 },
        { name: 'Hemocromatosis, Wilson y déficit de alfa-1-antitripsina', heat: 2 },
        { name: 'Reactivación del VHB en inmunodeprimidos', heat: 1 },
        { name: 'Hepatitis autoinmune y fallo hepático agudo', heat: 1 },
        { name: 'Hepatotoxicidad (amoxicilina-clavulánico, paracetamol)', heat: 1 },
      ],
      keys: [
        'VHB: HBsAg = infección; anti-HBc IgM = aguda; anti-HBs aislado = vacunado; anti-HBs + anti-HBc = curado. HBeAg y el ADN viral miden la replicación.',
        'Antes de quimioterapia, rituximab o biológicos: serología del VHB. Si HBsAg positivo, o anti-HBc positivo con rituximab, profilaxis con entecavir o tenofovir.',
        'VHC: hoy se cura en más del 95 % con antivirales de acción directa pangenotípicos durante 8-12 semanas. VHA y VHE: fecal-oral; el VHE puede cronificarse en inmunodeprimidos y ser grave en embarazadas.',
        'Hemocromatosis (HFE, C282Y): saturación de transferrina alta primero, luego ferritina. Tratamiento con flebotomías. Wilson: joven con hepatopatía y clínica neuropsiquiátrica, ceruloplasmina baja, anillo de Kayser-Fleischer.',
        'Alfa-1-antitripsina: enfisema panacinar basal más hepatopatía; en la biopsia, glóbulos PAS positivos resistentes a diastasa en los hepatocitos.',
        'Hepatitis autoinmune: mujer, IgG alta, ANA/anti-músculo liso (tipo 1) o anti-LKM1 (tipo 2); corticoides + azatioprina. Fallo hepático agudo: encefalopatía + INR ≥1,5 sin hepatopatía previa; N-acetilcisteína y valorar trasplante urgente.',
      ],
      trap: 'Un cirrótico que bebe puede tener también otra hepatopatía: la pregunta 14 del 2026 escondía un déficit de alfa-1-antitripsina en la autopsia de un alcohólico.',
    },
    {
      id: 'intestino',
      code: 'MAL',
      name: 'Intestino: malabsorción, diarrea y anatomía',
      shortName: 'Malabsorción',
      tier: 'media',
      perYear: [0, 2, 1, 1, 2, 0, 2, 0, 0, 0, 0, 4],
      lastExamReserve: 0,
      pages: 12,
      focus:
        'Llevaba 4 años sin preguntas y en 2026 dio 4: celiaquía (HLA), elastasa fecal, colitis colágena y el ligamento de Treitz. Temas cortos y fáciles de sumar.',
      hotspots: [
        { name: 'Celiaquía: serología, HLA-DQ2/DQ8 y biopsia', heat: 2 },
        { name: 'Colitis microscópica (colágena y linfocítica)', heat: 2 },
        { name: 'Esteatorrea: insuficiencia pancreática frente a malabsorción intestinal', heat: 2 },
        { name: 'Sobrecrecimiento bacteriano y biopsias características', heat: 1 },
        { name: 'Microbiota, trasplante fecal y anatomía intestinal', heat: 1 },
      ],
      keys: [
        'Celiaquía: anticuerpos antitransglutaminasa IgA con IgA total, y biopsia duodenal (atrofia, linfocitos intraepiteliales) comiendo gluten. En adultos la biopsia sigue siendo necesaria.',
        'HLA-DQ2/DQ8 casi siempre presente en celíacos, pero también en un tercio de la población: su valor es negativo (si no lo tiene, es muy improbable). Útil en familiares y en casos dudosos o con dieta ya retirada.',
        'Esteatorrea con dolor epigástrico, alcohol o pancreatitis previa: elastasa fecal baja = insuficiencia pancreática exocrina → enzimas pancreáticas.',
        'Colitis microscópica: mujer mayor de 50 con diarrea acuosa y colonoscopia normal. Colágena (banda de colágeno >10 µm) o linfocítica (>20 linfocitos intraepiteliales/100 células). Fármacos implicados: IBP, AINE, ISRS. Budesonida.',
        'Biopsias que dan el diagnóstico: Whipple (macrófagos PAS positivos), abetalipoproteinemia (enterocitos con grasa), agammaglobulinemia (sin células plasmáticas), linfangiectasia (linfáticos dilatados).',
        'Sobrecrecimiento bacteriano: asas ciegas, diabetes, esclerodermia, hipoclorhidria. Déficit de B12 con fólico normal o alto; test de aliento; rifaximina.',
        'C. difficile recurrente: el trasplante de microbiota fecal es la indicación mejor establecida.',
      ],
      trap: 'La elastasa fecal es la primera prueba en heces para la insuficiencia pancreática; el aclaramiento de alfa-1-antitripsina fecal es para la enteropatía pierde-proteínas.',
    },
    {
      id: 'abdomen-agudo',
      code: 'ABD',
      name: 'Abdomen agudo: apendicitis, diverticulitis e isquemia intestinal',
      shortName: 'Abdomen agudo',
      tier: 'alta',
      perYear: [1, 1, 2, 2, 1, 1, 0, 1, 2, 0, 1, 2],
      lastExamReserve: 0,
      pages: 12,
      focus:
        'Una pregunta al año, casi siempre con imagen. En 2026: colitis isquémica tras cirugía aórtica (TC) y neumoperitoneo por perforación (radiografía).',
      hotspots: [
        { name: 'Isquemia mesentérica aguda y colitis isquémica', heat: 2 },
        { name: 'Diverticulitis: clasificación de Hinchey y tratamiento', heat: 2 },
        { name: 'Apendicitis aguda: clínica, diagnóstico y manejo', heat: 2 },
        { name: 'Perforación de víscera hueca y neumoperitoneo', heat: 2 },
        { name: 'Traumatismo abdominal', heat: 1 },
      ],
      keys: [
        'Isquemia mesentérica aguda: dolor intenso con exploración anodina en un anciano con FA (embolia de la mesentérica superior). Angio-TC urgente; revascularización y resección del intestino no viable.',
        'Colitis isquémica: la forma más frecuente de isquemia intestinal; ancianos, dolor cólico y rectorragia; ángulo esplénico y sigma. Típica tras reparar un aneurisma aórtico (se pierde la mesentérica inferior). Suele resolverse con medidas de soporte; si hay gangrena, colectomía.',
        'No oclusiva: situaciones de bajo gasto, UCI, vasopresores o digoxina.',
        'Diverticulitis no complicada: TC para confirmar; en inmunocompetentes estables, tratamiento ambulatorio incluso sin antibiótico. Absceso mayor de 4-5 cm → drenaje percutáneo. Peritonitis purulenta o fecal (Hinchey III-IV) → cirugía (Hartmann o resección con anastomosis).',
        'Apendicitis: dolor periumbilical que migra a la fosa ilíaca derecha, anorexia, fiebre. Ecografía en niños y embarazadas, TC en adultos dudosos. Apendicectomía (laparoscópica); plastrón → antibiótico y drenaje si hay absceso.',
        'Neumoperitoneo: aire bajo el diafragma en la radiografía de tórax en bipedestación o, si no puede levantarse, en decúbito lateral izquierdo con rayo horizontal. Casi siempre perforación de úlcera: cirugía urgente.',
      ],
      trap: 'Dolor desproporcionado a la exploración = isquemia mesentérica hasta que se demuestre lo contrario; si además hay acidosis láctica, se llega tarde.',
    },
    {
      id: 'complicaciones',
      code: 'CPL',
      name: 'Complicaciones de la cirugía y cirugía mínimamente invasiva',
      shortName: 'Complicaciones',
      tier: 'alta',
      perYear: [3, 0, 1, 0, 0, 1, 0, 2, 0, 2, 2, 0],
      lastExamReserve: 0,
      pages: 8,
      focus:
        'Tema de cirugía "transversal" que se ha asentado: 2 preguntas en 2022, 2024 y 2025. En 2026 lo más cercano fue el control de daños (clasificado en Trauma).',
      hotspots: [
        { name: 'Prevención de la infección quirúrgica (bundles)', heat: 3 },
        { name: 'Clasificación de las heridas y profilaxis antibiótica', heat: 2 },
        { name: 'Fiebre postoperatoria según el día', heat: 2 },
        { name: 'Dehiscencia de anastomosis', heat: 1 },
      ],
      keys: [
        'Fiebre postoperatoria por días: las primeras 48 h, respuesta inflamatoria o atelectasia; a partir del 3.er día, infecciones nosocomiales (orina, neumonía, flebitis) y TEP; del 4.º al 7.º, infección de herida o dehiscencia de la anastomosis.',
        'Herida limpia (sin abrir tracto digestivo, respiratorio ni urinario), limpia-contaminada (apertura controlada), contaminada (vertido de contenido digestivo o inflamación aguda) y sucia (pus, perforación antigua).',
        'Profilaxis antibiótica: en los 60 min previos a la incisión, habitualmente cefazolina; dosis única o como mucho 24 h (48 h en cirugía cardiaca). No se prolonga "por si acaso".',
        'Bundle de infección quirúrgica: no rasurar (si hace falta, cortar con maquinilla eléctrica), clorhexidina alcohólica al 2 %, normotermia, control de la glucemia y profilaxis bien administrada.',
        'Dehiscencia de anastomosis: fiebre, dolor e íleo hacia el 5.º-7.º día, a veces con salida de contenido intestinal por el drenaje. TC; drenaje o reintervención según la repercusión.',
        'Laparoscopia: menos dolor, menos infección de herida y recuperación más rápida; el neumoperitoneo con CO₂ reduce el retorno venoso y puede dar hipercapnia.',
      ],
    },
    {
      id: 'pared',
      code: 'HER',
      name: 'Patología de la pared abdominal',
      shortName: 'Hernias',
      tier: 'alta',
      perYear: [1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 2, 2],
      lastExamReserve: 0,
      pages: 6,
      focus:
        'Dos preguntas en cada uno de los tres últimos MIR (2024, 2025 y 2026), tras años casi sin aparecer. En 2026, una diástasis de rectos con imagen y una hernia reductible.',
      hotspots: [
        { name: 'Hernia inguinal y crural: tipos, complicaciones y cirugía', heat: 3 },
        { name: 'Reductible, incoercible, incarcerada y estrangulada', heat: 3 },
        { name: 'Diástasis de rectos, Spiegel, eventración', heat: 2 },
        { name: 'Técnicas con y sin malla', heat: 2 },
      ],
      keys: [
        'Inguinal indirecta: sale por el orificio inguinal profundo, lateral a los vasos epigástricos, por persistencia del conducto peritoneovaginal; es la más frecuente en ambos sexos. Directa: medial a los epigástricos, por debilidad de la fascia transversalis (triángulo de Hesselbach).',
        'Crural: por debajo del ligamento inguinal y medial a la vena femoral; más en mujeres y con más riesgo de estrangularse → operar siempre.',
        'Reductible: vuelve con el decúbito o manualmente. Incoercible: no vuelve pero conserva la irrigación. Estrangulada: compromiso vascular (dolor intenso, dureza, eritema, obstrucción) → cirugía urgente.',
        'Reparación: con malla sin tensión (Lichtenstein) o laparoscópica (TEP o TAPP, de elección en las bilaterales y las recidivadas tras cirugía abierta). Las técnicas sin malla (Shouldice) son historia.',
        'Diástasis de rectos: separación de los rectos sin orificio herniario, típica tras embarazos (sobre todo múltiples); no se estrangula; fisioterapia.',
        'Spiegel: por la línea semilunar, lateral al recto, a menudo interparietal y difícil de palpar (ecografía o TC). Eventración: a través de una cicatriz quirúrgica previa.',
      ],
      trap: 'Una hernia que se modifica con Valsalva y desaparece al tumbarse es reductible: no la conviertas en complicada por el dolor o la edad.',
    },
    {
      id: 'anal',
      code: 'PRO',
      name: 'Patología anal y perianal',
      shortName: 'Proctología',
      tier: 'media',
      perYear: [1, 0, 1, 1, 0, 0, 0, 0, 1, 2, 1, 0],
      lastExamReserve: 0,
      pages: 6,
      focus: 'Sube en los últimos años (4 preguntas entre 2023 y 2025) y en 2026 no cayó ninguna: buen candidato para 2027.',
      hotspots: [
        { name: 'Fisura anal: localización y tratamiento escalonado', heat: 3 },
        { name: 'Absceso y fístula perianal', heat: 2 },
        { name: 'Hemorroides: grados y tratamiento', heat: 2 },
        { name: 'Dolor anorrectal funcional e incontinencia', heat: 1 },
      ],
      keys: [
        'Fisura anal: dolor intenso al defecar con rectorragia escasa; casi siempre en la línea media posterior. Fisuras laterales o múltiples → pensar en Crohn, sífilis, VIH o cáncer.',
        'Tratamiento de la fisura: fibra, baños de asiento y relajantes del esfínter (nitroglicerina o diltiazem tópicos), toxina botulínica; si fracasa, esfinterotomía lateral interna (cuidado con la incontinencia en mujeres).',
        'Absceso perianal: dolor, tumoración y fiebre → drenaje quirúrgico siempre; el antibiótico solo no basta. Tras drenarlo puede quedar una fístula.',
        'Fístula: interesfinteriana y transesfinteriana baja → fistulotomía; altas o complejas → sedal o técnicas que preservan el esfínter.',
        'Hemorroides internas (por encima de la línea pectínea, indoloras, sangran) por grados: I-II → dieta y ligadura con bandas; III-IV → hemorroidectomía. Trombosis de hemorroide externa en menos de 72 h: exéresis del trombo.',
      ],
    },
    {
      id: 'obstruccion',
      code: 'OBS',
      name: 'Obstrucción intestinal y vólvulos',
      shortName: 'Obstrucción',
      tier: 'media',
      perYear: [0, 1, 3, 0, 0, 0, 2, 0, 0, 2, 1, 0],
      lastExamReserve: 0,
      pages: 8,
      focus: 'Aparece a rachas, casi siempre como caso clínico con radiografía. Causas por tramos, vólvulos y prótesis de colon.',
      hotspots: [
        { name: 'Causas de obstrucción: bridas en delgado, cáncer en grueso', heat: 2 },
        { name: 'Vólvulo de sigma y de ciego', heat: 2 },
        { name: 'Pseudoobstrucción (Ogilvie)', heat: 1 },
        { name: 'Prótesis de colon en la obstrucción neoplásica', heat: 1 },
      ],
      keys: [
        'Intestino delgado: la causa más frecuente son las bridas (cirugía previa), después las hernias. Sin signos de estrangulación: dieta absoluta, sonda nasogástrica, sueroterapia y contraste hidrosoluble (diagnóstico y terapéutico).',
        'Intestino grueso: la causa más frecuente es el cáncer colorrectal. Con válvula ileocecal competente hay riesgo de perforación del ciego (más de 12 cm).',
        'Vólvulo de sigma: anciano, estreñido o institucionalizado; "grano de café" en la radiografía. Devolvulación endoscópica y cirugía electiva después. Si hay isquemia o fracasa → cirugía urgente.',
        'Vólvulo de ciego: más joven, se trata con cirugía (hemicolectomía derecha).',
        'Ogilvie: dilatación del colon sin obstáculo en pacientes graves o posoperados → corregir la causa, neostigmina y descompresión endoscópica.',
        'Cáncer de colon izquierdo obstructivo: prótesis como puente a la cirugía programada o paliativa; alternativa, cirugía urgente (Hartmann).',
      ],
    },
    {
      id: 'pancreatitis',
      code: 'PCT',
      name: 'Pancreatitis aguda y crónica',
      shortName: 'Pancreatitis',
      tier: 'baja',
      perYear: [0, 1, 2, 1, 0, 1, 1, 0, 1, 0, 0, 1],
      lastExamReserve: 0,
      pages: 10,
      focus: 'Menos de una pregunta al año. En 2026, el abordaje escalonado de la necrosis infectada.',
      hotspots: [
        { name: 'Pancreatitis aguda: diagnóstico, gravedad y tratamiento', heat: 2 },
        { name: 'Necrosis infectada y colecciones: step-up', heat: 2 },
        { name: 'Pancreatitis crónica y autoinmune', heat: 1 },
      ],
      keys: [
        'Diagnóstico con 2 de 3: dolor típico, amilasa o lipasa más de 3 veces lo normal, imagen compatible. La TC no se pide al ingreso salvo duda; se hace a las 72-96 h si la evolución es mala.',
        'Gravedad (Atlanta): leve sin fallo orgánico; moderada con fallo transitorio (<48 h) o complicaciones locales; grave con fallo orgánico persistente (>48 h).',
        'Tratamiento: fluidoterapia moderada (Ringer lactato, sin excesos), analgesia y nutrición enteral precoz. Sin antibióticos profilácticos. Si es biliar con colangitis → CPRE urgente; colecistectomía en el mismo ingreso en las leves.',
        'Necrosis infectada (gas en la colección, fiebre, empeoramiento a partir de la 2.ª-3.ª semana): antibiótico (carbapenem) y abordaje escalonado: drenaje endoscópico o percutáneo y necrosectomía mínimamente invasiva, esperando a que se encapsule.',
        'Pancreatitis crónica: alcohol y tabaco; dolor, diabetes y esteatorrea; calcificaciones. Enzimas pancreáticas y abandono de tóxicos. Autoinmune: IgG4 alta, páncreas "en salchicha", responde a corticoides.',
      ],
    },
  ],
  insights: [
    {
      icon: 'trending_up',
      title: 'Un año muy cargado',
      body: 'El MIR 2026 trajo 26 preguntas de Digestivo y Cirugía General (+2 de reserva), frente a una media de 21 desde 2015: la cifra más alta desde 2017.',
    },
    {
      icon: 'content_cut',
      title: 'La cirugía ya pesa tanto como la medicina',
      body: 'Plástica, pared abdominal y complicaciones quirúrgicas suman 18 preguntas en los tres últimos MIR con solo 20 páginas. Plástica (3 en 2026, 4 en 2025) es el tema con mejor rendimiento por página.',
    },
    {
      icon: 'image',
      title: 'Siete imágenes de Digestivo',
      body: 'Casi un tercio de las 25 imágenes del examen fueron de esta asignatura: TC (colitis isquémica), foto clínica (diástasis de rectos, linfedema), ecografía y colangio-RM, frotis, biopsia hepática y radiografía con neumoperitoneo.',
    },
    {
      icon: 'trending_down',
      title: 'Lo clásico médico, a la baja',
      body: 'Estómago lleva 0 preguntas de 2023 a 2025 y solo 1 en 2026; hepatitis y otras hepatopatías, de 2,7 a 0,6 al año. Son 54 páginas: estúdialas con esquemas.',
    },
    {
      icon: 'report',
      title: 'Dos preguntas polémicas',
      body: 'La 13 (acantocitos en un cirrótico) fue anulada y la 208 (encefalopatía hepática, de reserva) impugnada: ¿antibióticos a ciegas o amonio? Ninguna de las dos se mide de rutina.',
    },
    {
      icon: 'hub',
      title: 'Digestivo también en otras asignaturas',
      body: 'Cirugía bariátrica (Endocrino), control de daños (Trauma), colecistitis con BLEE (Infecciosas), trombosis mesentérica en la HPN (Hematología) y vacuna de la hepatitis A (Preventiva).',
    },
  ],
  plan: [
    {
      title: '1.ª vuelta · Los pilares',
      subtitle: 'Casi la mitad de las preguntas. Cáncer colorrectal y EII, estudiados juntos (cribado y vigilancia).',
      topicIds: ['ccr', 'eii', 'esofago', 'biliar', 'plastica'],
      days: 6,
    },
    {
      title: '2.ª vuelta · Máxima rentabilidad',
      subtitle: 'Cirugía corta y muy preguntada, más las complicaciones de la cirrosis y el hepatocarcinoma.',
      topicIds: ['pancreas-tumores', 'pared', 'complicaciones', 'abdomen-agudo', 'cirrosis', 'higado-tumores'],
      days: 5,
    },
    {
      title: '3.ª vuelta · Pasada rápida',
      subtitle: 'Esquemas y tablas: lo justo de cada enfermedad. Estómago y hepatitis, sin detalles.',
      topicIds: ['intestino', 'anal', 'obstruccion', 'pancreatitis', 'estomago', 'hepatopatias'],
      days: 3,
    },
  ],
  questions: [
    {
      number: 3,
      kind: 'bloque',
      topicId: 'abdomen-agudo',
      tag: 'Abdomen agudo · Isquemia intestinal',
      stem: 'Ingresa una paciente de 83 años para tratamiento de aneurisma de aorta abdominal de 50mm de diámetro, por crecimiento rápido en los últimos 6 meses. Entre sus antecedentes destaca: hipertensión arterial, dislipemia, portadora de marcapasos por bloqueo auriculo-ventricular completo como antecedentes. Veinticuatro horas tras la cirugía la paciente presenta distensión, dolor abdominal y rectorragias, acompañado de leucocitosis 32.100μl, con el 95% de neutrófilos y 278 de LDH como únicas alteraciones analíticas, por lo que se realiza un angio-tomografia computerizada, con la siguiente imagen (IMAGEN 3). ¿Cuál es el diagnóstico más probable?',
      imageUrl: 'https://pub-a0af2de03fec4dd2b89a37964efd1716.r2.dev/questions/2026/3.png',
      options: [
        'Isquemia mesentérica aguda.',
        'Isquemia mesentérica crónica.',
        'Isquemia mesentérica no oclusiva.',
        'Colitis isquémica.',
      ],
      correct: 4,
      explanation:
        'Rectorragia y dolor a las 24 h de reparar un aneurisma aórtico: colitis isquémica por pérdida de la mesentérica inferior. La TC muestra el colon descendente engrosado. La isquemia mesentérica aguda afecta al delgado y da dolor desproporcionado, sin rectorragia precoz.',
    },
    {
      number: 4,
      kind: 'bloque',
      topicId: 'pared',
      tag: 'Pared abdominal · Imagen',
      stem: 'Mujer de 36 años que acude a la consulta por una tumoración a nivel abdominal. Como antecedentes destaca que es alérgica a penicilinas, es exfumadora y que tuvo una diabetes gestacional durante un embarazo gemelar. A la exploración observas los siguientes hallazgos (IMAGEN 4). ¿Cuál es el diagnóstico más probable?',
      imageUrl: 'https://pub-a0af2de03fec4dd2b89a37964efd1716.r2.dev/questions/2026/4.png',
      options: [
        'Eventración con ‘pérdida de derecho a domicilio’.',
        'Hernia epigástrica.',
        'Hernia de Spiegel.',
        'Diástasis de rectos.',
      ],
      correct: 4,
      explanation:
        'Abultamiento en la línea media tras un embarazo gemelar, sin cirugía previa: diástasis de rectos. No hay orificio ni saco, así que no es una hernia y no se estrangula. Eventración exige cicatriz; Spiegel es lateral.',
    },
    {
      number: 5,
      kind: 'bloque',
      topicId: 'biliar',
      tag: 'Vía biliar · Imagen',
      stem: 'Varón de 58 años con antecedente de colelitiasis en una ecografía abdominal que se hizo por otra causa. Refiere dolor abdominal continuo en epigastrio – hipocondrio derecho que irradia hacia la espalda. El dolor le ha comenzado tras la ingesta y ha cedido parcialmente tras tomar un espasmolítico. Así mismo refiere que se nota un poco amarillo y que la orina es muy oscura. Constantes: Tensión arterial 140/75mmHg; Frecuencia cardiaca 100lpm; Temperatura 36,8ºC. A la exploración presenta dolor a la palpación en hipocondrio derecho con signo de Murphy negativo. En la analítica de sangre: Bilirrubina total de 4 mg/dl con bilirrubina directa de 3,5 mg/dl, amilasa y lipasa normal, no tiene leucocitosis. ¿Cuál es la sospecha diagnóstica y tratamiento que aplicarías?: Usa las imágenes de ayuda (IMÁGENES 5a y 5b).',
      imageUrl: 'https://pub-a0af2de03fec4dd2b89a37964efd1716.r2.dev/questions/2026/5.png',
      options: [
        'Cólico biliar por colelitiasis y Colecistectomía.',
        'Cólico biliar por coledocolitiasis, CPRE (Colangiopancreatografia retrógrada endoscópica) y colecistectomía.',
        'Colangitis y CPRE (Colangiopancreatografia retrógrada endoscópica).',
        'Neoplasia de vía biliar extrahepática y cirugía oncológica.',
      ],
      correct: 2,
      explanation:
        'Cólico, ictericia con bilirrubina directa, sin fiebre ni leucocitosis: coledocolitiasis. La clave es la clínica; la ecografía muestra la litiasis vesicular y la colangio-RM es la prueba para confirmarla en el colédoco. CPRE con extracción y colecistectomía después. Sin fiebre no hay colangitis.',
    },
    {
      number: 13,
      kind: 'bloque',
      topicId: 'cirrosis',
      tag: 'Cirrosis · Anulada',
      stem: 'Acude a urgencias un varón de 57 años, diagnosticado de una cirrosis etílica, sin descompensaciones previas, que mantiene un consumo de 2-3 cervezas al día. Ha comenzado con ictericia indolora en la última semana. En la exploración física únicamente destacan una franca ictericia cutánea y mucosa y ligeros edemas en ambas extremidades inferiores, sin ascitis. En la analítica encontramos hemoglobina: 11 g/dL, volumen corpuscular medio: 113 fL, Plaquetas 63*10⁹/L, AST: 90 UI/L, ALT: 35 UI/L, gamma-glutamiltransferasa: 60 UI/L, bilirrubina total: 10 mg/dL, bilirrubina conjugada: 2.5 mg/dL, albúmina: 36 g/L, gammaglobulinas: 16 g/dL, ferritina: 500 mcg/L, saturación de transferrina: 59%, haptoglobina menor de 8 mg/dL. La morfología de sangre periférica es la que se muestra en la imagen (IMAGEN 13). ¿Cuál es su diagnóstico?',
      imageUrl: 'https://pub-a0af2de03fec4dd2b89a37964efd1716.r2.dev/questions/2026/13.png',
      options: [
        'Hepatitis alcohólica.',
        'Hemocromatosis.',
        'Anemia hemolítica autoinmune.',
        'Acantocitosis.',
      ],
      correct: 4,
      explanation:
        'ANULADA. Cirrótico alcohólico con hemólisis (bilirrubina indirecta, haptoglobina indetectable): la oficial provisional era la 4, anemia por acantocitos ("células en espuela") de la hepatopatía avanzada. Pero el frotis del cuadernillo no permite distinguir bien los acantocitos, "acantocitosis" es un hallazgo más que un diagnóstico y la hepatitis alcohólica también encajaba.',
    },
    {
      number: 14,
      kind: 'bloque',
      topicId: 'hepatopatias',
      tag: 'Hepatopatías · Histología',
      stem: 'Varón de 55 años con antecedentes de consumo de alcohol mayor de 100 g/día desde la juventud, diagnosticado de enfermedad hepática crónica. Ingresa por una hemorragia digestiva alta por varices esofágicas, falleciendo a las 48 horas. Se realiza una autopsia. Macroscópicamente el hígado es micronodular. En la imagen microscópica llama la atención la presencia de glóbulos que se tiñen de forma intensa con la tinción de PAS (IMAGEN 14). ¿A qué corresponden esos glóbulos de la imagen?',
      imageUrl: 'https://pub-a0af2de03fec4dd2b89a37964efd1716.r2.dev/questions/2026/14.png',
      options: [
        'Vacuolas lipídicas.',
        'Hialina de Mallory.',
        'Alfa-1-antitripsina.',
        'Megamitocondrias.',
      ],
      correct: 3,
      explanation:
        'Glóbulos intensamente PAS positivos en los hepatocitos = alfa-1-antitripsina retenida (déficit, alelo Z). La hialina de Mallory es eosinófila y no es intensamente PAS positiva; la grasa se ve como vacuolas vacías.',
    },
    {
      number: 16,
      kind: 'bloque',
      topicId: 'plastica',
      tag: 'Plástica · Linfedema',
      stem: 'Mujer de 63 años de edad con diagnóstico de cáncer de endometrio estadio I. Ha sido intervenida mediante histerectomía radical más linfadenectomía pélvica y para-aórtica, finalizando con radioterapia. En la exploración física se objetiva un signo de Stemmer positivo. Tras visualizar la imagen (IMAGEN 16), ¿cuál de estas opciones considera que es la correcta?',
      imageUrl: 'https://pub-a0af2de03fec4dd2b89a37964efd1716.r2.dev/questions/2026/16.png',
      options: [
        'La paciente presenta una linfangitis, que se tratará mediante pauta de amoxicilina-clavulánico durante 10 días.',
        'La paciente tiene un lipedema, que se tratará con actividad física de bajo impacto con el objetivo de mejorar la circulación.',
        'La paciente presenta un linfedema, que se tratará mediante prenda de presoterapia a medida y drenaje linfático manual.',
        'La paciente presenta una sospecha de trombosis venosa profunda en la extremidad, por lo que solicitaremos un estudio de imagen con doppler vascular para confirmar el diagnóstico.',
      ],
      correct: 3,
      explanation:
        'Edema crónico tras linfadenectomía y radioterapia con Stemmer positivo: linfedema secundario. Terapia descongestiva: drenaje linfático manual y prenda de compresión a medida. El lipedema respeta los pies y tiene Stemmer negativo.',
    },
    {
      number: 23,
      kind: 'bloque',
      topicId: 'abdomen-agudo',
      tag: 'Abdomen agudo · Radiografía',
      stem: 'Paciente de 53 años sin antecedentes de interés que acude a urgencias por epigastralgia intensa que irradia difusamente al resto del abdomen. Había consultado en urgencias 3 días antes y se le dio el alta con paracetamol que fue efectivo. Reacude ahora por persistencia del dolor con sensación distérmica, náuseas y vómitos que condicionan la ingesta oral. En la exploración tiene un abdomen duro con dolor difuso que mejora con la flexión ventral del tronco. Se le realiza una radiografía de abdomen en la que se observa lo que muestra la imagen (IMAGEN 23). ¿Cuál es la principal sospecha diagnóstica?',
      imageUrl: 'https://pub-a0af2de03fec4dd2b89a37964efd1716.r2.dev/questions/2026/23.png',
      options: [
        'Obstrucción de intestino grueso.',
        'Perforación gástrica.',
        'Suboclusión de intestino delgado.',
        'Íleo adinámico.',
      ],
      correct: 2,
      explanation:
        'Epigastralgia que evoluciona a abdomen en tabla: perforación de víscera hueca (típicamente úlcera péptica). La radiografía en decúbito lateral con rayo horizontal busca aire libre; en la imagen no es muy llamativo, así que pesa la clínica (la TC es más sensible). Cirugía urgente.',
    },
    {
      number: 76,
      kind: 'bloque',
      topicId: 'plastica',
      tag: 'Plástica · Quemaduras',
      stem: '¿Cuál de las siguientes afirmaciones sobre las quemaduras de espesor parcial profundo es correcta?',
      options: [
        'Se caracterizan por dolor intenso y eritema marcado, sin formación de ampollas.',
        'Afectan solo la epidermis y suelen sanar sin dejar cicatriz.',
        'Presentan destrucción de la epidermis y dermis reticular, con pérdida de sensibilidad y mayor riesgo de infección.',
        'No requieren injerto cutáneo ya que cicatrizan espontáneamente en menos de una semana.',
      ],
      correct: 3,
      explanation:
        'La quemadura dérmica profunda destruye epidermis y dermis reticular: menos dolor (hipoestesia), más infección, cura en más de 3 semanas y suele necesitar injerto. Las demás opciones describen quemaduras superficiales.',
    },
    {
      number: 77,
      kind: 'bloque',
      topicId: 'plastica',
      tag: 'Plástica · Expansión tisular',
      stem: 'Respecto a la técnica de expansión tisular, la razón más frecuente de fallos es:',
      options: [
        'Bolsa pequeña respecto al expansor.',
        'Llenado del expansor de forma muy lenta.',
        'Mal cálculo de las medidas necesarias.',
        'Llenado del expansor de forma rápida.',
      ],
      correct: 1,
      explanation:
        'La causa más frecuente de fallo es un bolsillo pequeño para el expansor: queda plegado, tensa la piel y acaba exponiéndose o extruyéndose.',
    },
    {
      number: 94,
      kind: 'bloque',
      topicId: 'eii',
      tag: 'EII · Cirugía urgente',
      stem: 'La cirugía de elección en un paciente con un brote severo de colitis ulcerosa que desarrolla un megacolon tóxico es:',
      options: [
        'Proctocolectomía total + reservorio ileoanal+ ileostomía lateral.',
        'Proctocolectomía total + ileostomía terminal.',
        'Colectomía total + ileostomía terminal.',
        'Colectomía total + anastomosis ileorrectal.',
      ],
      correct: 3,
      explanation:
        'Megacolon tóxico: colectomía total (subtotal) con ileostomía terminal, dejando el recto. El reservorio ileoanal se hace después, en cirugía programada.',
    },
    {
      number: 95,
      kind: 'bloque',
      topicId: 'pancreas-tumores',
      tag: 'Páncreas · Whipple',
      stem: 'La complicación más frecuente y grave de la duodenopancreatectomía cefálica es:',
      options: [
        'Hemorragia.',
        'Absceso intrabdominal.',
        'Fístula pancreática.',
        'Infección herida.',
      ],
      correct: 3,
      explanation:
        'La fístula pancreática es la complicación más frecuente y grave de la duodenopancreatectomía; de ella derivan abscesos y hemorragias tardías por pseudoaneurisma.',
    },
    {
      number: 97,
      kind: 'bloque',
      topicId: 'pancreas-tumores',
      tag: 'Páncreas · NMPI',
      stem: 'Indica la afirmación FALSA en relación con la neoplasia mucinosa papilar intraductal (NPIM) del páncreas:',
      options: [
        'Se localiza en cabeza y cuerpo, pero el 10% es multifocal (skiplesions).',
        'Se realiza una pancreatectomia total, ya que maligniza y es multifocal.',
        'Existen tres tipos (I: ducto principal; II: rama secundaria III: mixto).',
        'En el tipo I durante la CPRE (Colangiopancreatografía retrógrada endoscópica) se produce salida de moco de la papila.',
      ],
      correct: 2,
      explanation:
        'Falsa la 2: la NMPI no se trata con pancreatectomía total por sistema; se reseca según localización y solo si hay criterios (estigmas de alto riesgo, ducto principal). El resto es cierto.',
    },
    {
      number: 98,
      kind: 'bloque',
      topicId: 'pared',
      tag: 'Pared abdominal · Hernia inguinal',
      stem: 'Varón de 83 años que acude a Urgencias Generales por cuadro de dolor a nivel inguinal izquierdo de 2 horas de evolución, con tumoración blanda y móvil asociada a la exploración. Se modifica con las maniobras de Valsalva y desaparece con el decúbito. Elija la respuesta CORRECTA:',
      options: [
        'El paciente presenta una hernia inguinal reductible a la exploración.',
        'El paciente presenta una hernia inguinal incoercible a la exploración.',
        'El paciente presenta una hernia inguinal con pérdida de derecho a domicilio en la exploración.',
        'El paciente presenta una hernia inguinal estrangulada a la exploración.',
      ],
      correct: 1,
      explanation:
        'Se modifica con Valsalva y desaparece al tumbarse: reductible. Estrangulada implica compromiso vascular; incoercible, que no se reduce aunque esté bien irrigada.',
    },
    {
      number: 99,
      kind: 'bloque',
      topicId: 'ccr',
      tag: 'CCR · Cirugía',
      stem: 'Entre los principios oncológicos en el tratamiento del cáncer de colon se encuentran todas las siguientes afirmaciones, EXCEPTO:',
      options: [
        'Hay que realizar una resección intestinal con márgenes quirúrgicos amplios.',
        'No hace falta hacer linfadenectomía.',
        'Realizar resecciones en bloque si existe sospecha de infiltración de órganos vecinos.',
        'En ocasiones se da tratamiento neoadyuvante con quimioterapia previa a la cirugía.',
      ],
      correct: 2,
      explanation:
        'La linfadenectomía regional (al menos 12 ganglios, ligando el pedículo en su origen) es obligatoria en el cáncer de colon. Márgenes amplios, resección en bloque y neoadyuvancia seleccionada son principios correctos.',
    },
    {
      number: 100,
      kind: 'bloque',
      topicId: 'esofago',
      tag: 'Esófago · Zenker',
      stem: '¿Cuál de las siguientes afirmaciones es correcta en relación al divertículo faringoesofágico de Zenker?',
      options: [
        'Se trata de un divertículo por tracción.',
        'Es más frecuente en pacientes jóvenes.',
        'Entre sus síntomas se encuentran: disfagia, regurgitación y halitosis.',
        'La localización especifica en la parte posterior de la faringe se denomina triángulo de Farabeuf.',
      ],
      correct: 3,
      explanation:
        'Divertículo de pulsión por el triángulo de Killian, en ancianos, con disfagia, regurgitación y halitosis. No es de tracción ni de jóvenes; Farabeuf es un triángulo vascular del cuello.',
    },
    {
      number: 144,
      kind: 'bloque',
      topicId: 'intestino',
      tag: 'Malabsorción · Esteatorrea',
      stem: 'Un paciente de 56 años ha perdido 10kg en el último año coincidiendo con un notable aumento de las deposiciones que son pastosas, amarillas y flotantes. Presenta dolor epigástrico-mesogástrico postprandial que limita la ingesta. Hace 4 años recibió tratamiento erradicador de Helicobacter Pylori por úlcera duodenal recidivante. ¿Cuál de las siguientes exploraciones en heces le parece más útil en el primer estudio para orientar el diagnóstico?',
      options: [
        'Estudio coproparasitario.',
        'Aclaramiento fecal de alfa-1-antitripsina.',
        'Determinación de antígeno de Helicobacter Pylori en heces.',
        'Cuantificación de elastasa fecal.',
      ],
      correct: 4,
      explanation:
        'Esteatorrea con dolor epigástrico posprandial y pérdida de peso: sospecha de insuficiencia pancreática exocrina. La primera prueba en heces es la elastasa fecal.',
    },
    {
      number: 147,
      kind: 'bloque',
      topicId: 'estomago',
      tag: 'Estómago · Úlcera por AINE',
      stem: 'Mujer de 72 años, con antecedentes personales de enfermedad pulmonar obstructiva crónica y artrosis. Toma antiinflamatorio no esteroideo clásico diario y ácido acetilsalicílico a baja dosis. Acude a urgencias por presentar melenas. En la endoscopia de urgencias se objetiva una úlcera gástrica Forrest III en curvatura menor, con biopsias negativas para malignidad y Helicobacter pylori negativo. Conducta más adecuada a medio plazo:',
      options: [
        'Reiniciar antiinflamatorio no esteroideo y ácido acetilsalicílico igual, con inhibidor de la bomba de protones 2 semanas.',
        'Mantener inhibidor de la bomba de protones a dosis plenas, reevaluar la necesidad de antiinflamatorio no esteroideo y realizar endoscopia de control para confirmar cicatrización.',
        'Cambiar inhibidor de la bomba de protones por anti-h2.',
        'Cambiar antiinflamatorio no esteroideo por paracetamol e inhibidor de la bomba de protones a demanda.',
      ],
      correct: 2,
      explanation:
        'Úlcera gástrica Forrest III por AINE: IBP a dosis plena, replantear el AINE y endoscopia de control con biopsias para confirmar la cicatrización (obligatoria en las gástricas).',
    },
    {
      number: 148,
      kind: 'bloque',
      topicId: 'esofago',
      tag: 'Esófago · Barrett',
      stem: 'Paciente varón de 58 años, con historia de más de 15 años de pirosis y regurgitación, tratada de forma intermitente con inhibidores de la bomba de protones. No fumador, índice de masa corporal de 35 kg/m². Consulta por empeoramiento de los síntomas. Se realiza gastroscopia en la que se objetiva un segmento de mucosa columnar de 5 cm por encima de la unión esófago-gástrica (C3M5), sin lesiones nodulares. Se toman biopsias con el resultado siguiente: metaplasia intestinal con displasia de bajo grado en dos cilindros. La revisión por un patólogo experto en esófago de Barrett confirma la presencia de displasia de bajo grado verdadera. Según las recomendaciones actuales de manejo del Barrett con displasia confirmada, la actitud MÁS adecuada es:',
      options: [
        'Mantener inhibidor de la bomba de protones a demanda y repetir endoscopia de control a los 3 años.',
        'Repetir endoscopia en 12 meses sin otras medidas, dado que es displasia de bajo grado.',
        'Ofrecer ablación por radiofrecuencia mediante endoscopia en centro experto, manteniendo inhibidor de la bomba de protones.',
        'Indicar esofaguectomía subtotal profiláctica por el riesgo acumulado de carcinoma.',
      ],
      correct: 3,
      explanation:
        'Displasia de bajo grado confirmada por un patólogo experto: ablación por radiofrecuencia en centro experto manteniendo el IBP. La esofaguectomía no está indicada.',
    },
    {
      number: 149,
      kind: 'bloque',
      topicId: 'esofago',
      tag: 'Esófago · ERGE',
      stem: 'Paciente de 52 años, con pirosis y dolor retroesternal. Se le realiza una endoscopia alta en la que se observa esofagitis erosiva grado C de Los Ángeles. ¿Cuál de las siguientes afirmaciones es CORRECTA?',
      options: [
        'Un ciclo corto de 2 semanas de inhibidor de la bomba de protones sería suficiente para asegurar la curación mucosa esofágica.',
        'Debe plantearse tratamiento de mantenimiento con inhibidor de la bomba de protones a largo plazo.',
        'Una vez curada la esofagitis, no existe riesgo aumentado de Barrett.',
        'El tratamiento de elección son los anti-h2 nocturnos como monoterapia.',
      ],
      correct: 2,
      explanation:
        'Esofagitis grado C: IBP 8 semanas y mantenimiento a largo plazo, por su alta recaída. Los anti-H2 son inferiores y la curación no elimina el riesgo de Barrett.',
    },
    {
      number: 150,
      kind: 'bloque',
      topicId: 'eii',
      tag: 'EII · CU frente a Crohn',
      stem: 'Respecto a la diferenciación entre colitis ulcerosa y colitis de Crohn, señale la opción MÁS correcta:',
      options: [
        'La afectación parcheada y el recto respetado obligan siempre a diagnosticar Crohn.',
        'La presencia de granulomas no caseificantes en biopsia colónica es fuertemente sugestiva de Crohn.',
        'La afectación continua desde el recto hasta el ciego es típica de Crohn colónica pura.',
        'La afectación del íleon terminal nunca aparece en la colitis ulcerosa.',
      ],
      correct: 2,
      explanation:
        'Los granulomas no caseificantes sugieren fuertemente Crohn. La afectación continua desde el recto es de CU, y en la pancolitis ulcerosa puede haber ileítis por reflujo.',
    },
    {
      number: 151,
      kind: 'bloque',
      topicId: 'intestino',
      tag: 'Malabsorción · Celiaquía',
      stem: 'Paciente con 23 años, quiere saber si es celíaco, porque su madre lo es. Pregunta sobre el estudio genético. Respecto al papel del estudio genético HLA-DQ2/DQ8 en enfermedad celíaca, señale la opción CORRECTA:',
      options: [
        'Es una prueba diagnóstica confirmatoria cuando es positiva.',
        'Un resultado negativo para HLA-DQ2 y HLA-DQ8 hace muy improbable el diagnóstico de enfermedad celíaca.',
        'Solo es útil en el cribado poblacional general.',
        'Debe solicitarse de rutina en todos los pacientes con serología positiva.',
      ],
      correct: 2,
      explanation:
        'El HLA-DQ2/DQ8 tiene gran valor predictivo negativo: si es negativo, la celiaquía es muy improbable. Positivo no confirma nada (lo lleva un tercio de la población).',
    },
    {
      number: 152,
      kind: 'bloque',
      topicId: 'pancreatitis',
      tag: 'Pancreatitis · Necrosis infectada',
      stem: 'Paciente con pancreatitis aguda grave por litiasis biliar, necrosis extensa estéril del cuerpo y cola. A las 3 semanas, fiebre, dolor persistente, PCR elevada. En el TAC de abdomen con contraste se observa una colección encapsulada con niveles líquido-aire y necrosis pancreática. ¿Cuál es la conducta MÁS adecuada?',
      options: [
        'Laparotomía urgente con necrosectomía abierta.',
        'Mantener tratamiento conservador, la presencia de gas no sugiere infección.',
        'Abordaje escalonado: drenaje mínimamente invasivo (endoscópico/percutáneo) guiado y necrosectomía diferida si es necesario.',
        'Esclerosis percutánea con alcohol absoluto.',
      ],
      correct: 3,
      explanation:
        'Gas en una necrosis encapsulada a las 3 semanas = infección. Antibiótico y abordaje escalonado: drenaje endoscópico o percutáneo y necrosectomía diferida si hace falta.',
    },
    {
      number: 153,
      kind: 'bloque',
      topicId: 'ccr',
      tag: 'CCR · Síndrome de Lynch',
      stem: 'En relación con el cribado de cáncer colorrectal en el síndrome de Lynch (MLH1/MSH2), señale la opción CORRECTA:',
      options: [
        'El paciente debe hacerse colonoscopias cada 10 años desde los 50 años.',
        'El paciente debe hacerse colonoscopias cada 5 años desde los 40 años o 10 años antes del caso más joven.',
        'El paciente debe hacerse colonoscopias cada 1-2 años desde los 20-25 años o 25 años antes del caso más joven en la familia.',
        'El paciente debe hacerse colonoscopias solo si test de sangre oculta en heces es positivo.',
      ],
      correct: 3,
      explanation:
        'Lynch (MLH1/MSH2): colonoscopia cada 1-2 años desde los 20-25 años. Las otras pautas son del cribado poblacional o de familiares de casos esporádicos.',
    },
    {
      number: 154,
      kind: 'bloque',
      topicId: 'intestino',
      tag: 'Diarrea · Colitis microscópica',
      stem: 'Mujer de 55 años con diarrea acuosa crónica, no sanguinolenta, de meses de evolución, con colonoscopia macroscópicamente normal. Las biopsias colónicas muestran infiltrado inflamatorio de la lámina propia con banda colágena subepitelial engrosada >10 μm. El diagnóstico MÁS probable es:',
      options: [
        'Colitis ulcerosa izquierda.',
        'Enfermedad de Crohn colónica.',
        'Colitis microscópica linfocítica.',
        'Colitis microscópica colágena.',
      ],
      correct: 4,
      explanation:
        'Diarrea acuosa crónica, colonoscopia normal y banda de colágeno subepitelial >10 µm: colitis colágena. La linfocítica no tiene banda y sí muchos linfocitos intraepiteliales.',
    },
    {
      number: 155,
      kind: 'bloque',
      topicId: 'eii',
      tag: 'EII · Vigilancia del CCR',
      stem: 'Paciente de 32 años con colitis ulcerosa extensa de 10 años de evolución, en remisión clínica y endoscópica, sin displasia en colonoscopias previas. ¿Cree que debe realizarse colonoscopias de revisión para la vigilancia endoscópica del cáncer colorrectal?',
      options: [
        'No precisa vigilancia hasta los 20 años de evolución.',
        'Debe realizarse colonoscopia con cromoendoscopia dirigida cada 3-5 años.',
        'Solo es necesario control si presenta antecedentes familiares de CCR.',
        'La biopsia aleatoria en todos los segmentos ha sustituido completamente a la cromoendoscopia.',
      ],
      correct: 2,
      explanation:
        'Colitis extensa de más de 8 años: vigilancia con cromoendoscopia; en remisión y sin factores de riesgo, cada 3-5 años. Con colangitis esclerosante, anual.',
    },
    {
      number: 171,
      kind: 'bloque',
      topicId: 'intestino',
      tag: 'Intestino · Anatomía',
      stem: 'Una mujer de 53 años es diagnosticada de vólvulo de intestino medio e isquemia intestinal. Se realiza laparotomía para liberar la obstrucción intestinal. ¿Cuál de las siguientes estructuras se usa como punto de referencia anatómico para determinar la posición de la unión duodenoyeyunal?',
      options: [
        'Ligamento de Treitz.',
        'Arteria mesentérica superior.',
        'Arteria mesentérica inferior.',
        'Ligamento frenocólico',
      ],
      correct: 1,
      explanation:
        'El ligamento de Treitz marca el ángulo duodenoyeyunal: referencia en la cirugía de la malrotación y el vólvulo de intestino medio y límite entre la hemorragia alta y la baja.',
    },
    {
      number: 206,
      kind: 'reserva',
      topicId: 'ccr',
      tag: 'CCR · Cáncer de recto',
      stem: 'Un hombre de 62 años es diagnosticado de adenocarcinoma de recto medio, confirmado por biopsia endoscópica. La tomografía computarizada toracoabdominopélvica no muestra metástasis a distancia. ¿Qué prueba de imagen es más adecuada para identificar la mejor opción terapéutica local en este paciente?',
      options: [
        'Tomografía computerizada de abdomen y pelvis con contraste intravenoso y angiografía (angio TAC).',
        'Tomografía por emisión de positrones de pelvis combinada con Tomografía computerizada (PET/TC).',
        'Resonancia magnética pélvica (RMN) con secuencias de alta resolución del mesorrecto, con o sin contraste.',
        'Ecografía combinada abdomino-pélvica y endorrectal.',
      ],
      correct: 3,
      explanation:
        'La RM pélvica de alta resolución estadifica el recto (T, fascia mesorrectal, ganglios) y decide entre cirugía directa o neoadyuvancia. Puntuó al sustituir a una anulada.',
    },
    {
      number: 208,
      kind: 'reserva',
      topicId: 'cirrosis',
      tag: 'Cirrosis · Impugnada',
      stem: 'Mujer de 67 años diagnosticada de cirrosis hepática, con antecedentes de descompensaciones ascíticas en tratamiento con espironolactona y furosemida. Su familia la trae a urgencias por alteración del nivel de conciencia. La paciente se encuentra ligeramente desorientada en tiempo y espacio y somnolienta. Tiene asterixis franca. ¿Cuál de las siguientes medidas NO se encuentra indicada a su ingreso?',
      options: [
        'Paracentesis diagnóstica.',
        'Medición de los niveles plasmáticos de amoniaco.',
        'Administración de lactulosa por vía oral.',
        'Antibioterapia de amplio espectro.',
      ],
      correct: 4,
      explanation:
        'Encefalopatía grado II en un cirrótico: buscar el desencadenante (paracentesis diagnóstica) y lactulosa. La oficial dice que sobran los antibióticos a ciegas, pero medir el amonio tampoco está indicado de rutina: por eso se impugnó.',
    },
    {
      number: 93,
      kind: 'frontera',
      topicId: 'complicaciones',
      tag: 'Endocrinología · Cirugía bariátrica',
      stem: 'En relación a las indicaciones de cirugía bariátrica, señale la correcta.',
      options: [
        'El IMC es la mejor medida de correlación entre exceso de peso y gravedad de la enfermedad.',
        'El IMC es una medida útil, pero que no se utiliza para la indicación de cirugía bariátrica.',
        'El punto de corte del IMC es de 55, independientemente de las enfermedades asociadas.',
        'Paciente con IMC por debajo de 35 y enfermedades metabólicas poco controladas se pueden beneficiar de la cirugía bariátrica.',
      ],
      correct: 4,
      explanation:
        'Indicada con IMC ≥40, o ≥35 con comorbilidad, y también con IMC 30-35 si la diabetes u otras enfermedades metabólicas están mal controladas (cirugía metabólica).',
    },
    {
      number: 96,
      kind: 'frontera',
      topicId: 'complicaciones',
      tag: 'Traumatología · Control de daños',
      stem: 'La estrategia de control de daños pretende evitar:',
      options: [
        'Hipertermia, acidosis y coagulopatía.',
        'Acidosis, hipotermia y coagulopatía.',
        'Hipotermia, alcalosis y coagulopatía.',
        'Hipertermia, alcalosis y coagulopatía.',
      ],
      correct: 2,
      explanation:
        'Cirugía abreviada en el politraumatizado inestable para cortar la tríada letal: hipotermia, acidosis y coagulopatía. La reparación definitiva se hace a las 24-48 h.',
    },
    {
      number: 35,
      kind: 'frontera',
      topicId: 'biliar',
      tag: 'Infecciosas · Colecistitis gangrenosa',
      stem: 'Mujer de 73 años que ingresa en el hospital por cuadro de fiebre, dolor en hipocondrio derecho e hipotensión. Tras reanimación con fluidos se agrava la hipotensión y requiere intubación y conexión a ventilación mecánica. Se realiza una Tomografía axial computerizada (TAC) de abdomen observándose datos de colecistitis gangrenosa con gas y engrosamiento irregular de la pared. Se realiza colecistostomía de drenaje e ingresa en la Unidad de cuidados intensivos (UCI). Se inicia tratamiento con piperacilina-tazobactam. Dos días después la paciente se encuentra en disfunción multiorgánica (SOFA 11 puntos), conectada a ventilación mecánica y requiriendo noradrenalina y vasopresina. Se recibe el siguiente hemocultivo: ANTIBIOGRAMA: CMI (mg/L) Ampicilina R >8 Amoxicilina-Clav R > 32 Piperacilina-Taz S 4 Cefotaxima R >2 Ceftazidima R >8 Cefepime R >8 Azteronam R >4 Ertapenem S < 0,12 Imipenem S <1 Meropenem S < 0,12 Gentamicina S <2 Ciprofloxacino S 0,25 Con estos datos, ¿cuál es la respuesta CORRECTA respecto al tratamiento antibiótico de esta paciente?',
      options: [
        'Mantener piperacilina-tazobactam.',
        'Mantener piperacilina-tazobactam añadiendo un aminoglucósico.',
        'Suspender piperacilina-tazobactam e iniciar meropenem.',
        'Suspender piperacilina-tazobactam e iniciar ciprofloxacino.',
      ],
      correct: 3,
      explanation:
        'Bacteriemia por una enterobacteria resistente a las cefalosporinas de 3.ª generación (probable BLEE) en shock séptico: cambiar a meropenem, aunque piperacilina-tazobactam salga sensible in vitro.',
    },
    {
      number: 143,
      kind: 'frontera',
      topicId: 'abdomen-agudo',
      tag: 'Hematología · Trombosis mesentérica',
      stem: 'Un paciente de 39 años que presenta emisión recidivante de orina rojiza, episodios repetidos de dolor abdominal de etiología no diagnosticada, acude a urgencias con un nuevo episodio de dolor abdominal intenso. En los estudios realizados en urgencias se objetiva una trombosis venosa mesentérica. ¿Cuál es el diagnóstico de sospecha que considera más probable?',
      options: [
        'Hemoglobinuria paroxística nocturna.',
        'Síndrome antifosfolípido.',
        'Coproporfiria eritropoyética.',
        'Fiebre mediterránea familiar.',
      ],
      correct: 1,
      explanation:
        'Orina oscura recurrente, dolor abdominal y trombosis venosa en un sitio atípico (mesentérica): hemoglobinuria paroxística nocturna. Se confirma con citometría (déficit de CD55/CD59).',
    },
    {
      number: 186,
      kind: 'frontera',
      topicId: null,
      tag: 'Endocrinología · Obesidad',
      stem: '¿Cuál de las siguientes afirmaciones es correcta al comparar el tratamiento farmacológico y el tratamiento quirúrgico de la obesidad según las guías clínicas actuales?',
      options: [
        'El tratamiento farmacológico logra una pérdida de peso superior al tratamiento quirúrgico en pacientes con obesidad grave.',
        'La cirugía bariátrica está indicada únicamente en pacientes con obesidad grado I sin comorbilidades.',
        'El tratamiento farmacológico es más eficaz que la cirugía para mejorar la diabetes tipo 2 en pacientes con obesidad.',
        'La cirugía bariátrica logra mayores reducciones de peso y mejoría de comorbilidades que el tratamiento farmacológico en obesidad grave.',
      ],
      correct: 4,
      explanation:
        'En la obesidad grave, la cirugía bariátrica consigue más pérdida de peso y más mejoría de la diabetes y otras comorbilidades que los fármacos.',
    },
    {
      number: 31,
      kind: 'frontera',
      topicId: 'hepatopatias',
      tag: 'Preventiva · Hepatitis A',
      stem: '¿Cuál de los siguientes NO se considera un grupo de riesgo que requiera vacunación frente al Virus de la Hepatitis A?',
      options: [
        'Pacientes diagnosticados de VIH.',
        'Pacientes candidatos a trasplante hepático.',
        'Pacientes diagnosticados de asplenia anatómica o disfunción esplénica grave.',
        'Pacientes diagnosticados de enfermedad hepática crónica.',
      ],
      correct: 3,
      explanation:
        'La vacuna de la hepatitis A se indica en hepatopatía crónica, candidatos a trasplante hepático y VIH, entre otros; la asplenia no es indicación (lo es para neumococo, meningococo y Haemophilus).',
    },
  ],
  sourcesNote:
    'Pesos calculados con el recuento de preguntas MIR de Digestivo y Cirugía General de 2015 a 2025, agrupadas en 17 bloques temáticos propios, y con la clasificación de las preguntas del MIR 2026 (cuaderno oficial, versión 0). Las respuestas del MIR 2026 están contrastadas con las definitivas publicadas tras las impugnaciones: la 13 fue anulada y la 208 (reserva) impugnada; según las normas del examen, las reservas sustituyen por orden a las anuladas, así que la 206 acabó puntuando. La previsión para el MIR 2027 es una media ponderada (70 % los últimos 5 MIR, 30 % los anteriores): orientativa, no una predicción exacta. La extensión de cada tema es aproximada.',
}
