import type { StudyGuide } from '@/types/studyGuide'

// Pesos: preguntas MIR 2015-2025 por tema + clasificación propia del MIR 2026
// (cuaderno oficial, versión 0). Respuestas del 2026 contrastadas con las definitivas publicadas tras las impugnaciones.
export const NEUROLOGIA_GUIDE: StudyGuide = {
  subjectId: 'neurologia',
  title: 'Neurología y Neurocirugía',
  subtitle: 'Qué estudiar, en qué orden y cuánto pesa cada cosa en el MIR',
  targetExam: 'MIR 2027',
  lastExam: 'MIR 2026',
  historyRange: '2015–2025',
  perYear: [
    { year: 2015, count: 13 },
    { year: 2016, count: 12 },
    { year: 2017, count: 12 },
    { year: 2018, count: 15 },
    { year: 2019, count: 12 },
    { year: 2020, count: 14 },
    { year: 2021, count: 13 },
    { year: 2022, count: 21 },
    { year: 2023, count: 14 },
    { year: 2024, count: 11 },
    { year: 2025, count: 16 },
    { year: 2026, count: 10 },
  ],
  lastExamTotal: 10,
  lastExamReserveTotal: 2,
  topics: [
    {
      id: 'neurocirugia',
      code: 'NCX',
      name: 'Neurocirugía',
      shortName: 'Neurocirugía',
      tier: 'imprescindible',
      perYear: [2, 1, 0, 4, 3, 2, 1, 8, 4, 4, 3, 3],
      lastExamReserve: 1,
      pages: 26,
      focus:
        'El tema más preguntado de la asignatura: casi 3 preguntas por año. Columna, TCE, tumores y LCR (hidrocefalia e HII) concentran casi todo.',
      hotspots: [
        { name: 'Patología raquimedular: lumbalgia, hernias, estenosis de canal', heat: 3 },
        { name: 'Tumores cerebrales: metástasis, meningioma, glioma, fosa posterior infantil', heat: 3 },
        { name: 'Hipertensión intracraneal, hidrocefalia normotensiva e HII', heat: 3 },
        { name: 'TCE: Glasgow, hematoma epidural vs subdural, fractura de base', heat: 2 },
        { name: 'Facomatosis (NF1, NF2, esclerosis tuberosa, VHL)', heat: 2 },
        { name: 'Lesión medular traumática y anomalías del desarrollo', heat: 1 },
      ],
      keys: [
        'Hernia lumbar: la más frecuente es L5-S1. La hernia posterolateral comprime la raíz de abajo: L4-L5 → L5 (andar de talones, dorso del pie) y L5-S1 → S1 (andar de puntillas, reflejo aquíleo, borde externo del pie).',
        'Lumbalgia sin signos de alarma: tratamiento conservador, sin imagen y manteniendo la actividad. Alarma: cáncer previo, fiebre, edad avanzada, pérdida de peso, déficit progresivo. Cola de caballo (retención urinaria, anestesia en silla de montar) = cirugía urgente.',
        'Estenosis de canal lumbar: claudicación neurógena que obliga a sentarse o flexionar el tronco (la vascular mejora solo con pararse y tiene pulsos disminuidos).',
        'Metástasis: el tumor intracraneal más frecuente; primario más habitual el pulmón (mama en mujeres). Unión córtico-subcortical, captación en anillo con mucho edema. Múltiples → radioterapia; única, accesible y con enfermedad controlada → cirugía.',
        'Meningioma: el primario más frecuente, extraaxial, benigno, mujer, cola dural. La resección completa puede curarlo; el grado OMS marca recidiva y radioterapia.',
        'Glioblastoma: primario maligno más frecuente del adulto. Cirugía máxima + radioterapia + temozolomida; MGMT metilado = mejor respuesta. En niños manda la fosa posterior: pilocítico (el más frecuente) y meduloblastoma (maligno, vermis, disemina por LCR).',
        'Epidural: arteria meníngea media, fractura temporal, lente biconvexa, intervalo lúcido → cirugía urgente. Subdural: venas puente, semiluna; el crónico en ancianos, alcohólicos o anticoagulados, con clínica fluctuante semanas después.',
        'Hidrocefalia normotensiva (Hakim-Adams): marcha (lo primero y lo que más mejora), incontinencia y demencia. Ventriculomegalia sin atrofia; punción evacuadora de prueba → derivación.',
        'HII (pseudotumor cerebri): mujer joven obesa, cefalea y papiledema, imagen normal, LCR con presión alta y composición normal. Riesgo de pérdida visual; acetazolamida y pérdida de peso.',
        'Facomatosis: NF1 (manchas café con leche, neurofibromas, nódulos de Lisch, glioma óptico), NF2 (schwannomas vestibulares bilaterales), esclerosis tuberosa (angiofibromas, astrocitoma subependimario de células gigantes, espasmos infantiles), VHL (hemangioblastoma con policitemia).',
      ],
      trap: 'La fístula de LCR se confirma con beta-2-transferrina (cayó en ORL en 2026). Y la dexametasona sirve para el edema vasogénico tumoral, no para el TCE.',
    },
    {
      id: 'ictus',
      code: 'ICT',
      name: 'Enfermedad cerebrovascular',
      shortName: 'Ictus',
      tier: 'imprescindible',
      perYear: [0, 1, 3, 3, 1, 2, 1, 3, 2, 1, 2, 0],
      lastExamReserve: 0,
      pages: 14,
      focus:
        'Casi 2 preguntas por año… y en 2026 no cayó ninguna. Es el tema con más papeletas de volver con fuerza en el MIR 2027.',
      hotspots: [
        { name: 'Ictus isquémico agudo: fibrinólisis, trombectomía, unidad de ictus', heat: 3 },
        { name: 'Hemorragia subaracnoidea y hemorragia intraparenquimatosa', heat: 3 },
        { name: 'Clínica por territorios vasculares (ACM, ACA, ACP, vertebrobasilar)', heat: 2 },
        { name: 'Prevención secundaria según etiología', heat: 2 },
        { name: 'Trombosis de senos venosos', heat: 1 },
      ],
      keys: [
        'ACM: hemiparesia faciobraquial, afasia si es hemisferio dominante, heminegligencia si no lo es, hemianopsia y mirada desviada hacia la lesión. ACA: pierna, abulia, incontinencia. ACP: hemianopsia con respeto macular y alexia sin agrafia.',
        'Lacunar: clínica pura (motora, sensitiva, ataxia-hemiparesia…) sin signos corticales: nunca afasia, hemianopsia ni negligencia. Se asocia a HTA.',
        'Vertebrobasilar = síndromes cruzados. Wallenberg (bulbar lateral, vertebral/PICA): Horner, ataxia e hipoalgesia facial homolaterales + hipoalgesia corporal contralateral, sin debilidad.',
        'Fase aguda: TC sin contraste para descartar sangrado. Fibrinólisis IV en ≤4,5 h (más allá solo con imagen de penumbra); TA <185/110 para fibrinolizar. Trombectomía solo si hay oclusión de gran vaso proximal (hasta 24 h con tejido salvable).',
        'Prevención secundaria: antiagregar el aterotrombótico y el lacunar; anticoagular el cardioembólico (FA → ACOD). Endarterectomía si la estenosis carotídea sintomática es del 70–99 %.',
        'Hematoma intraparenquimatoso: HTA → profundo (ganglios basales, tálamo, protuberancia, cerebelo); angiopatía amiloide → lobar en ancianos. Las profundas no se evacúan; la cerebelosa grande o con deterioro, sí.',
        'HSA: aneurisma sacular (el de comunicante anterior es el más frecuente). Cefalea en trueno → TC; si es normal y la sospecha alta, punción lumbar; después angiografía. Complicaciones: resangrado (precoz), vasoespasmo (días 4–14, nimodipino), hidrocefalia, hiponatremia.',
        'Parálisis de III par con midriasis y dolor = aneurisma de comunicante posterior hasta que se demuestre lo contrario.',
        'Disección carotídea: dolor cervical + Horner + ictus o amaurosis en joven. CADASIL: NOTCH3, lacunares, migraña con aura y leucopatía en joven.',
      ],
      trap: 'El ictus lacunar no da clínica cortical; si el caso tiene afasia o hemianopsia, no es lacunar.',
    },
    {
      id: 'semiologia',
      code: 'SEM',
      name: 'Semiología',
      shortName: 'Semiología',
      tier: 'imprescindible',
      perYear: [2, 3, 0, 1, 1, 1, 1, 3, 2, 2, 2, 2],
      lastExamReserve: 1,
      pages: 22,
      focus:
        'Pocas preguntas por página, pero es la base del resto de temas y cae casi siempre: localización de lesiones, vías y pares craneales.',
      hotspots: [
        { name: 'Síndromes lobares y afasias', heat: 3 },
        { name: 'Pares craneales (III par, VII central vs periférico, trigémino)', heat: 3 },
        { name: 'Síndromes alternos del tronco (Wallenberg)', heat: 2 },
        { name: 'Síndromes medulares', heat: 2 },
        { name: 'Primera vs segunda motoneurona, tono y reflejos', heat: 2 },
        { name: 'Neurofisiología: placa motora y contracción muscular', heat: 2 },
      ],
      keys: [
        'Primera motoneurona: espasticidad que depende de la velocidad (en navaja), hiperreflexia, Babinski, sin atrofia precoz. Segunda: flacidez, arreflexia, atrofia y fasciculaciones. La rigidez extrapiramidal es constante en todo el recorrido (tubo de plomo, rueda dentada).',
        'Afasias: Broca (no fluente, comprende), Wernicke (fluente, no comprende), conducción (falla sobre todo la repetición), transcorticales (repetición conservada).',
        'Lóbulos: parietal dominante → Gerstmann; parietal no dominante → heminegligencia y anosognosia; temporal → cuadrantanopsia superior; parietal → inferior; occipital → hemianopsia con respeto macular y ceguera cortical con pupilas normales.',
        'Médula: Brown-Séquard (motor y posicional homolateral, dolor y temperatura contralateral); centromedular/siringomielia (disociación termoalgésica en capa); arteria espinal anterior (respeta los cordones posteriores).',
        'III par con midriasis = compresivo (aneurisma, herniación uncal); sin midriasis = isquémico (diabetes). La parálisis facial central respeta la frente.',
        'Neuralgia del trigémino: dolor lancinante de segundos en V2-V3 → carbamazepina. Tolosa-Hunt: oftalmoplejía dolorosa que responde a corticoides.',
        'Placa motora: la acetilcolina abre receptores nicotínicos (canales catiónicos, entra sobre todo Na⁺) y genera un potencial de placa local y graduado que dispara el potencial de acción muscular.',
      ],
      trap: 'Espasticidad = depende de la velocidad del movimiento. Rigidez = resistencia constante. Esta distinción cayó en 2026.',
    },
    {
      id: 'movimiento',
      code: 'MOV',
      name: 'Trastornos del movimiento',
      shortName: 'Movimiento',
      tier: 'alta',
      perYear: [2, 0, 2, 1, 1, 1, 2, 1, 2, 1, 3, 1],
      lastExamReserve: 0,
      pages: 8,
      focus:
        'Uno de los temas más rentables: solo 8 páginas y más de una pregunta al año. El Parkinson se lleva la mayoría.',
      hotspots: [
        { name: 'Enfermedad de Parkinson: diagnóstico y tratamiento', heat: 3 },
        { name: 'Parkinsonismos atípicos (PSP, AMS, DCL, corticobasal, fármacos)', heat: 2 },
        { name: 'Temblor esencial, Huntington, distonías', heat: 2 },
        { name: 'Síndrome de piernas inquietas', heat: 1 },
      ],
      keys: [
        'Parkinsonismo = bradicinesia + temblor de reposo o rigidez. Parkinson: inicio asimétrico y síntomas no motores precoces (hiposmia, estreñimiento, trastorno de conducta del sueño REM, depresión).',
        'Criterios MDS de apoyo: respuesta clara a levodopa, discinesias por levodopa, temblor de reposo y pérdida de olfato. Banderas rojas: caídas precoces, mala respuesta a levodopa, signos cerebelosos, parálisis de la mirada vertical.',
        'Tratamiento: levodopa es el más eficaz. Agonistas: más trastornos del control de impulsos. Fin de dosis (wearing-off) → acortar intervalos; discinesias pico de dosis → amantadina. Estimulación del subtalámico en <70 años sin deterioro cognitivo.',
        'PSP: caídas hacia atrás, parálisis supranuclear vertical, retrocolis. AMS: disautonomía + parkinsonismo/cerebelo. Cuerpos de Lewy: fluctuaciones, alucinaciones visuales, sensibilidad extrema a neurolépticos.',
        'Temblor esencial: postural y de acción, bilateral, familiar (AD), mejora con alcohol → propranolol o primidona.',
        'Huntington: AD, repetición CAG en el cromosoma 4, anticipación (sobre todo paterna), corea + psiquiatría + demencia, atrofia del caudado.',
        'Distonía focal → toxina botulínica. Piernas inquietas: descartar ferropenia (dar hierro si ferritina <75). Parkinsonismo en joven con clínica psiquiátrica → descartar Wilson.',
      ],
      trap: 'La ausencia de respuesta a levodopa va contra el Parkinson; la pérdida de olfato lo apoya.',
    },
    {
      id: 'epilepsia',
      code: 'EPI',
      name: 'Epilepsia',
      shortName: 'Epilepsia',
      tier: 'alta',
      perYear: [2, 1, 1, 1, 1, 3, 2, 1, 2, 1, 0, 1],
      lastExamReserve: 0,
      pages: 10,
      focus:
        'Una o dos preguntas casi todos los años. Clasificación, síndromes clásicos, diagnóstico diferencial y fármacos (sobre todo en el embarazo).',
      hotspots: [
        { name: 'Fármacos anticrisis: espectro, efectos adversos, embarazo', heat: 3 },
        { name: 'Síndromes: mioclónica juvenil, temporal mesial, ausencias, West', heat: 3 },
        { name: 'Clasificación de las crisis', heat: 2 },
        { name: 'Diagnóstico diferencial: síncope, crisis psicógenas, AGT', heat: 2 },
        { name: 'Estatus epiléptico y crisis sintomáticas agudas', heat: 1 },
      ],
      keys: [
        'Epilepsia: 2 crisis no provocadas separadas >24 h, o 1 crisis con alto riesgo de recurrencia (EEG epileptiforme o lesión en imagen).',
        'Síncope: desencadenante postural o vagal, pródromos, puede tener mioclonías breves y se recupera enseguida sin confusión. Crisis: confusión poscrítica y mordedura lateral de lengua. Crisis psicógena: ojos cerrados, movimientos asíncronos, EEG normal durante el episodio.',
        'Ausencias típicas: infancia, punta-onda a 3 Hz que provoca la hiperventilación → etosuximida o valproato. La carbamazepina las empeora.',
        'Mioclónica juvenil: adolescente con sacudidas matutinas, tónico-clónicas y ausencias, desencadenadas por falta de sueño → valproato (levetiracetam o lamotrigina en mujeres en edad fértil), tratamiento de por vida.',
        'Temporal mesial: esclerosis de hipocampo, antecedente de convulsiones febriles, aura epigástrica o déjà vu, automatismos. Si es refractaria → cirugía.',
        'West: espasmos + hipsarritmia + regresión → ACTH/corticoides o vigabatrina (de elección en la esclerosis tuberosa).',
        'Estatus: benzodiacepina a los 5 min → levetiracetam, valproato o fenitoína IV → anestesia en UCI.',
        'Embarazo: evitar valproato (teratógeno y dependiente de la dosis); de elección lamotrigina o levetiracetam, con ácido fólico. Los inductores (carbamazepina, fenitoína, fenobarbital) hacen fallar la anticoncepción hormonal.',
      ],
      trap: 'Que haya movimientos no la convierte en crisis: el síncope también puede dar mioclonías. La clave es la recuperación rápida sin confusión.',
    },
    {
      id: 'autoinmunes-snc',
      code: 'AUT',
      name: 'Enfermedades autoinmunes del SNC',
      shortName: 'Autoinmunes SNC',
      tier: 'alta',
      perYear: [1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1],
      lastExamReserve: 0,
      pages: 6,
      focus:
        'El tema más constante de la asignatura: una pregunta casi todos los años desde 2015, en solo 6 páginas. Esclerosis múltiple y encefalitis autoinmunes.',
      hotspots: [
        { name: 'Esclerosis múltiple: clínica, diagnóstico y tratamiento', heat: 3 },
        { name: 'Encefalitis autoinmunes (anti-NMDA, anti-LGI1)', heat: 2 },
        { name: 'Neuromielitis óptica y complicaciones de la inmunoterapia', heat: 1 },
      ],
      keys: [
        'EM: mujer de 20–40 años. Neuritis óptica retrobulbar, oftalmoplejía internuclear bilateral en joven, mielitis parcial, Lhermitte, empeoramiento con el calor (Uhthoff).',
        'Diagnóstico (McDonald): diseminación en espacio y tiempo. Las bandas oligoclonales IgG en LCR pueden sustituir a la diseminación temporal.',
        'LCR típico de EM: pleocitosis linfocitaria leve y proteínas normales o poco elevadas. Más de 50 células o proteínas >100 mg/dl → piensa en otra cosa.',
        'RM: lesiones periventriculares perpendiculares al cuerpo calloso, yuxtacorticales, infratentoriales y medulares; las que captan gadolinio están activas.',
        'Brote: metilprednisolona IV 3–5 días (acorta el brote, no cambia la evolución). Fondo: interferón, acetato de glatirámero, teriflunomida, dimetilfumarato; alta eficacia: natalizumab (riesgo de LMP), ocrelizumab (el único en la forma primaria progresiva), cladribina, alemtuzumab.',
        'Neuromielitis óptica: anti-AQP4, neuritis óptica grave + mielitis longitudinalmente extensa (≥3 segmentos). El interferón la empeora.',
        'Anti-NMDA: mujer joven con clínica psiquiátrica, crisis, discinesias orofaciales y disautonomía → busca un teratoma de ovario. Anti-LGI1: crisis distónicas faciobraquiales e hiponatremia.',
        'Los inhibidores de checkpoint pueden desencadenar miastenia, miositis, miocarditis, Guillain-Barré o encefalitis.',
      ],
      trap: 'Proteínas >100 mg/dl en el LCR van contra la EM (lo preguntaron en 2026).',
    },
    {
      id: 'demencias',
      code: 'DEM',
      name: 'Trastornos de la memoria y demencias',
      shortName: 'Demencias',
      tier: 'media',
      perYear: [0, 3, 1, 1, 1, 1, 4, 1, 0, 0, 1, 0],
      lastExamReserve: 0,
      pages: 6,
      focus:
        'Ojo con la tendencia: tras el pico de 2021 (4 preguntas) solo han caído 2 en los últimos 5 MIR. Sigue siendo corto y fácil de puntuar, pero ya no es fijo: estúdialo después de los temas al alza.',
      hotspots: [
        { name: 'Alzheimer: clínica, biomarcadores y tratamiento', heat: 3 },
        { name: 'Demencia frontotemporal y afasias primarias progresivas', heat: 2 },
        { name: 'Demencia con cuerpos de Lewy', heat: 2 },
        { name: 'Priones (Creutzfeldt-Jakob)', heat: 1 },
        { name: 'Amnesia global transitoria', heat: 1 },
      ],
      keys: [
        'Alzheimer: la más frecuente; empieza por la memoria episódica. Placas de β-amiloide y ovillos de tau. LCR: Aβ42 bajo y tau/p-tau altas. ApoE4 = factor de riesgo.',
        'Tratamiento: inhibidores de acetilcolinesterasa (donepezilo, rivastigmina, galantamina) en fase leve-moderada; memantina en moderada-grave.',
        'Cuerpos de Lewy: fluctuaciones, alucinaciones visuales, parkinsonismo y trastorno de conducta del sueño REM. Si un paciente con demencia empeora mucho con un antipsicótico → Lewy.',
        'Frontotemporal (variante conductual): paciente más joven con desinhibición, apatía, hiperoralidad y memoria respetada al principio. C9orf72 la relaciona con la ELA.',
        'Afasias primarias progresivas: logopénica (falla la repetición; suele ser Alzheimer), semántica (pierde el significado de las palabras), no fluente (agramatismo, apraxia del habla).',
        'Creutzfeldt-Jakob: demencia muy rápida + mioclonías; EEG con complejos periódicos, LCR 14-3-3 y RT-QuIC, RM en difusión con ribete cortical. Fallece en menos de un año.',
        'Busca siempre las causas tratables: hidrocefalia normotensiva, B12, hipotiroidismo, sífilis, hematoma subdural crónico.',
        'Amnesia global transitoria: amnesia anterógrada aislada con preguntas repetitivas, dura menos de 24 h y es benigna.',
      ],
      trap: 'Demencia + parkinsonismo: si la demencia empieza antes o en el primer año → Lewy; si llega años después → Parkinson con demencia.',
    },
    {
      id: 'cefalea',
      code: 'CEF',
      name: 'Cefalea',
      shortName: 'Cefalea',
      tier: 'media',
      perYear: [1, 1, 1, 0, 2, 1, 0, 2, 0, 0, 1, 1],
      lastExamReserve: 0,
      pages: 4,
      focus:
        'Tema corto y agradecido: 4 páginas, casi una pregunta al año. Diferenciar migraña, tensional y trigémino-autonómicas, y reconocer los signos de alarma.',
      hotspots: [
        { name: 'Cefaleas trigémino-autonómicas (cluster, hemicránea)', heat: 2 },
        { name: 'Cefaleas secundarias: pospunción, HII, carcinomatosis, arteritis', heat: 2 },
        { name: 'Migraña: tratamiento agudo y preventivo', heat: 2 },
        { name: 'Cefalea tensional', heat: 1 },
      ],
      keys: [
        'Signos de alarma: inicio brusco (en trueno), debut >50 años, cambia con la postura o Valsalva, despierta por la noche, fiebre, focalidad, papiledema, cáncer o inmunodepresión.',
        'Tensional: la más frecuente. Opresiva, bilateral, leve-moderada, no empeora con la actividad y sin náuseas. Profilaxis con amitriptilina.',
        'Migraña: unilateral, pulsátil, moderada-grave, empeora con la actividad, náuseas, fotofobia y sonofobia. Crisis: AINE o triptanes (no en cardiopatía isquémica). Profilaxis si hay varias crisis al mes: propranolol, topiramato, amitriptilina, flunarizina, anti-CGRP.',
        'Cluster: varón joven, dolor orbitario de 15–180 min con lagrimeo, rinorrea y Horner; el paciente está inquieto; predominio nocturno. Crisis: O₂ al 100 % y sumatriptán SC. Prevención: verapamilo.',
        'Hemicránea paroxística: crisis más cortas y frecuentes, más en mujeres, respuesta absoluta a indometacina.',
        'Arteritis de células gigantes: >50 años, claudicación mandibular, VSG alta → corticoides sin esperar a la biopsia.',
        'Cefalea pospunción: ortostática (mejora al tumbarse) → reposo, cafeína, parche hemático.',
      ],
      trap: 'Tensional = opresiva y bilateral; pulsátil con fotofobia = migraña (cayó en 2026).',
    },
    {
      id: 'miopatias',
      code: 'MIO',
      name: 'Miopatías',
      shortName: 'Miopatías',
      tier: 'baja',
      perYear: [0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0],
      lastExamReserve: 0,
      pages: 4,
      focus: 'Poco preguntado. Con Steinert y Duchenne cubres casi todo.',
      hotspots: [
        { name: 'Distrofia miotónica de Steinert', heat: 2 },
        { name: 'Duchenne / Becker', heat: 1 },
        { name: 'Oculofaríngea y mitocondriales', heat: 1 },
      ],
      keys: [
        'Steinert: AD, expansión CTG (DMPK). Miotonía, debilidad distal y facial, cataratas, calvicie frontal, hipogonadismo, trastornos de conducción cardíaca. La forma congénita se hereda de la madre.',
        'Duchenne: ligada al X (distrofina), maniobra de Gowers, pseudohipertrofia de gemelos, CK muy alta, miocardiopatía. Becker: igual pero más tardía y leve.',
        'Oculofaríngea: ptosis y disfagia en adulto mayor. Mitocondriales: herencia materna, fibras rojo-rasgadas.',
      ],
    },
    {
      id: 'placa-motora',
      code: 'PLM',
      name: 'Enfermedades de la placa motora',
      shortName: 'Placa motora',
      tier: 'baja',
      perYear: [0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 0],
      lastExamReserve: 0,
      pages: 4,
      focus:
        'Pocas preguntas directas, pero la miastenia aparece mucho de rebote en otras asignaturas (en 2026, en Oncología).',
      hotspots: [
        { name: 'Miastenia gravis: diagnóstico y tratamiento', heat: 2 },
        { name: 'Diagnóstico diferencial con Eaton-Lambert y botulismo', heat: 1 },
      ],
      keys: [
        'Miastenia: debilidad fluctuante que empeora con el esfuerzo; ptosis y diplopía; pupilas y reflejos normales. Anticuerpos anti-AChR (o anti-MuSK); EMG con respuesta decremental; TC de tórax para buscar timoma.',
        'Tratamiento: piridostigmina, inmunosupresores, timectomía (si hay timoma, o en generalizada seropositiva de 18–65 años). Crisis miasténica: IgIV o plasmaféresis.',
        'Empeoran la miastenia: aminoglucósidos, quinolonas, magnesio, betabloqueantes e inhibidores de checkpoint.',
        'Eaton-Lambert: presináptico (canales de calcio), asociado a carcinoma microcítico, debilidad proximal, disautonomía, reflejos que mejoran tras el ejercicio y respuesta incremental. Botulismo: parálisis descendente con midriasis.',
      ],
    },
    {
      id: 'neuropatias',
      code: 'NRP',
      name: 'Neuropatías',
      shortName: 'Neuropatías',
      tier: 'baja',
      perYear: [1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
      lastExamReserve: 0,
      pages: 6,
      focus: 'Céntrate en el Guillain-Barré y la neuropatía diabética; el resto, solo por encima.',
      hotspots: [
        { name: 'Síndrome de Guillain-Barré', heat: 2 },
        { name: 'Neuropatía diabética', heat: 1 },
      ],
      keys: [
        'Guillain-Barré: debilidad ascendente y arrefléxica tras una infección (Campylobacter). LCR con disociación albúmino-citológica; lo primero en el EMG es la abolición de la onda F. Tratamiento: IgIV o plasmaféresis (no corticoides); vigilar la capacidad vital.',
        'Neuropatía diabética: la más común es la polineuropatía sensitiva distal simétrica. Mononeuropatía típica: III par que respeta la pupila.',
        'PDIC: como un Guillain-Barré que dura más de 8 semanas; sí responde a corticoides.',
      ],
    },
    {
      id: 'nutricionales',
      code: 'NUT',
      name: 'Enfermedades nutricionales y metabólicas',
      shortName: 'Nutricionales',
      tier: 'baja',
      perYear: [2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
      lastExamReserve: 0,
      pages: 4,
      focus: 'Solo dos cosas, pero muy preguntables: Wernicke y la degeneración combinada subaguda.',
      hotspots: [
        { name: 'Encefalopatía de Wernicke', heat: 2 },
        { name: 'Degeneración combinada subaguda (B12)', heat: 2 },
      ],
      keys: [
        'Wernicke: oftalmoparesia, ataxia y confusión en alcohólico o desnutrido (también hiperemesis). Tiamina antes que la glucosa. Korsakoff: amnesia con fabulación.',
        'Déficit de B12: cordones posteriores + vía piramidal (Babinski con reflejos aquíleos abolidos). Si es tras cirugía bariátrica, piensa también en déficit de cobre.',
        'Mielinolisis pontina central: corrección demasiado rápida de una hiponatremia.',
      ],
    },
    {
      id: 'coma',
      code: 'COM',
      name: 'Coma y muerte encefálica',
      shortName: 'Coma',
      tier: 'baja',
      perYear: [0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0],
      lastExamReserve: 0,
      pages: 4,
      focus: 'Glasgow y signos que localizan la lesión. Se pregunta mucho en Urgencias.',
      hotspots: [
        { name: 'Escala de Glasgow', heat: 2 },
        { name: 'Pupilas y patrones respiratorios en el coma', heat: 1 },
        { name: 'Muerte encefálica', heat: 1 },
      ],
      keys: [
        'Glasgow: ojos 4, verbal 5, motora 6. Con ≤8, intubar.',
        'Pupilas: midriasis unilateral arreactiva = herniación uncal (III par); puntiformes = protuberancia u opiáceos; medias fijas = mesencéfalo; reactivas en el coma metabólico.',
        'Respiración: Cheyne-Stokes (diencéfalo o bihemisférico), hiperventilación neurógena central (mesencéfalo), apnéustica (protuberancia), atáxica (bulbo).',
        'Muerte encefálica: coma arreactivo, sin reflejos de tronco y con test de apnea positivo. La anisocoria obliga a replantear el diagnóstico.',
      ],
    },
    {
      id: 'motoneurona',
      code: 'MTN',
      name: 'Enfermedades de motoneurona',
      shortName: 'ELA',
      tier: 'baja',
      perYear: [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
      lastExamReserve: 0,
      pages: 2,
      focus: 'Casi no se pregunta directamente, pero la ELA es el ejemplo de 1.ª + 2.ª motoneurona.',
      hotspots: [{ name: 'ELA: signos combinados de primera y segunda motoneurona', heat: 1 }],
      keys: [
        'ELA: signos de primera y segunda motoneurona a la vez, sin alteraciones sensitivas ni de esfínteres y respetando los oculomotores. C9orf72 es la causa genética más frecuente. Riluzol.',
        'Atrofia muscular espinal: gen SMN1, solo segunda motoneurona; nusinersen.',
      ],
    },
    {
      id: 'ataxia',
      code: 'ATX',
      name: 'Ataxia',
      shortName: 'Ataxia',
      tier: 'baja',
      perYear: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      lastExamReserve: 0,
      pages: 2,
      focus: 'Ninguna pregunta en 11 años. Basta con la ataxia de Friedreich.',
      hotspots: [{ name: 'Ataxia de Friedreich', heat: 1 }],
      keys: [
        'Friedreich: AR, expansión GAA (frataxina). Ataxia + arreflexia + Babinski, pies cavos, escoliosis, diabetes y miocardiopatía hipertrófica (la causa de muerte).',
      ],
    },
  ],
  insights: [
    {
      icon: 'trending_down',
      title: 'Año flojo, no tendencia',
      body: 'El MIR 2026 trajo 10 preguntas de Neuro (+2 de reserva), frente a una media de 14. Desde 2015 ha oscilado entre 11 y 21: no des la asignatura por devaluada.',
    },
    {
      icon: 'crisis_alert',
      title: 'Ictus: cero en 2026',
      body: 'Es el 2.º tema más preguntado (casi 2 por año) y en 2026 no cayó ninguna. Es la mejor apuesta para el MIR 2027: llévalo perfecto.',
    },
    {
      icon: 'bolt',
      title: 'Preguntas cortas y de concepto',
      body: 'Casi todas fueron directas: tríada de Hakim, cefalea tensional, espasticidad, narcolepsia. Ni un caso largo ni una imagen. Premiaron saber lo clásico sin fallar.',
    },
    {
      icon: 'neurology',
      title: 'Lo que sube y lo que baja',
      body: 'Neurocirugía se ha más que duplicado (4,4 preguntas/año desde 2022 frente a 1,9 antes) y Semiología también sube. Demencias cae en picado (2 en 5 años) y Epilepsia baja.',
    },
    {
      icon: 'bedtime',
      title: 'Cayó algo fuera del temario habitual',
      body: 'La narcolepsia tipo 1 (hipocretina) entró en el bloque de Neuro aunque suele estudiarse con los trastornos del sueño. Repásala junto a esta asignatura.',
    },
    {
      icon: 'hub',
      title: 'Neuro también en otras asignaturas',
      body: 'Fístula de LCR (ORL), miastenia con inmunoterapia (Oncología), TCE con collarín (Urgencias), coma por opiáceos, red flags de lumbalgia… Lo que estudias aquí puntúa también allí.',
    },
  ],
  plan: [
    {
      title: '1.ª vuelta · Los pilares',
      subtitle: 'Casi la mitad de las preguntas. Entiende la semiología; no la memorices.',
      topicIds: ['neurocirugia', 'ictus', 'semiologia'],
      days: 5,
    },
    {
      title: '2.ª vuelta · Máxima rentabilidad',
      subtitle: 'Temas cortos que dan preguntas casi todos los años. Demencias, al final: va a la baja.',
      topicIds: ['movimiento', 'epilepsia', 'autoinmunes-snc', 'demencias', 'cefalea'],
      days: 4,
    },
    {
      title: '3.ª vuelta · Pasada rápida',
      subtitle: 'Lo justo: una idea clave por enfermedad. Añade la narcolepsia.',
      topicIds: ['placa-motora', 'neuropatias', 'miopatias', 'nutricionales', 'coma', 'motoneurona', 'ataxia'],
      days: 1,
    },
  ],
  questions: [
    {
      number: 70,
      kind: 'bloque',
      topicId: 'semiologia',
      tag: 'Semiología · Neurofisiología',
      stem: 'En relación con el potencial de placa terminal en la unión neuromuscular, ¿cuál de las siguientes afirmaciones es correcta?',
      options: [
        'Su amplitud depende de la suma temporal de los potenciales de acción en la fibra muscular.',
        'Se origina principalmente por la apertura de receptores nicotínicos para acetilcolina que permiten el flujo de Na⁺ y, en menor cantidad, de K⁺.',
        'Se genera cuando la acetilcolina activa conductos de Ca²⁺ dependientes de voltaje.',
        'Se propaga a lo largo de toda la fibra muscular como un potencial de acción independiente.',
      ],
      correct: 2,
      explanation:
        'El receptor nicotínico es un canal catiónico que se abre al unirse la ACh: entra mucho Na⁺ y sale algo de K⁺. El potencial de placa es local y graduado; no se propaga (el que se propaga es el potencial de acción que dispara).',
    },
    {
      number: 78,
      kind: 'bloque',
      topicId: 'neurocirugia',
      tag: 'Neurocirugía · Tumores',
      stem: 'Sobre los tumores cerebrales metastásicos o secundarios, indique la respuesta CORRECTA:',
      options: [
        'Son más infrecuentes que las neoplasias cerebrales primarias: sólo el 10% de los pacientes con diagnóstico de tumor cerebral.',
        'Típicamente se desarrollan durante la primera y segunda década de la vida.',
        'Las neoplasias que con más frecuencia dan implantes cerebrales son las de páncreas e hígado.',
        'Cuando existen metástasis cerebrales múltiples, el tratamiento quirúrgico para lograr la extirpación completa de todas las lesiones no suele ser una opción posible.',
      ],
      correct: 4,
      explanation:
        'Las metástasis son el tumor intracraneal más frecuente, sobre todo en adultos y con origen habitual en pulmón o mama. Si son múltiples, lo indicado es la radioterapia; la cirugía se reserva para la lesión única y accesible.',
    },
    {
      number: 79,
      kind: 'bloque',
      topicId: 'neurocirugia',
      tag: 'Neurocirugía · Tumores',
      stem: 'Con respecto al meningioma cerebral, indique la afirmación CORRECTA:',
      options: [
        'Son tumores bien definidos y extraaxiales, por lo que generalmente son extirpables de forma completa y esto puede ser curativo.',
        'Los pacientes deben hacerse un estudio genético antes de tener descendencia por la herencia autosómica dominante de estos tumores.',
        'Como son benignos, no hace falta un estudio anatomopatológico completo: el grado no influye en el tratamiento ni en el pronóstico.',
        'Las recidivas no dependen del grado tumoral y no son frecuentes.',
      ],
      correct: 1,
      explanation:
        'Es extraaxial y bien delimitado: la resección completa puede curarlo. El grado OMS sí importa, porque condiciona la recidiva y la necesidad de radioterapia. La mayoría son esporádicos (solo la NF2 los hereda).',
    },
    {
      number: 164,
      kind: 'bloque',
      topicId: 'autoinmunes-snc',
      tag: 'EM · Diagnóstico',
      stem: '¿Cuál de los siguientes hallazgos en el líquido cefalorraquídeo (LCR) hace cuestionar el diagnóstico de esclerosis múltiple?',
      options: [
        'Presencia de bandas oligoclonales.',
        'Pleocitosis leve linfocitaria.',
        'Hiperproteinorraquia >100 mg/dl.',
        'Índice IgG elevado.',
      ],
      correct: 3,
      explanation:
        'En la EM el LCR suele tener proteínas normales o poco elevadas y como mucho unas decenas de linfocitos. Bandas oligoclonales e índice IgG alto la apoyan; unas proteínas >100 mg/dl obligan a buscar otro diagnóstico.',
    },
    {
      number: 165,
      kind: 'bloque',
      topicId: 'neurocirugia',
      tag: 'Neurocirugía · Hidrocefalia',
      stem: '¿Cuál es la tríada clínica característica de la hidrocefalia normotensiva del adulto?',
      options: [
        'Trastorno de la marcha, incontinencia urinaria y deterioro cognitivo.',
        'Cefalea, vómitos y rigidez de nuca.',
        'Diplopía, papiledema y tinnitus pulsátil.',
        'Vómitos, bradicardia y alteración del nivel de conciencia.',
      ],
      correct: 1,
      explanation:
        'Tríada de Hakim-Adams. Las demás son meningismo (2), hipertensión intracraneal idiopática (3) y tríada de Cushing / HTIC grave (4).',
    },
    {
      number: 166,
      kind: 'bloque',
      topicId: null,
      tag: 'Sueño · Fuera del temario de Neuro',
      stem: 'En relación con la narcolepsia tipo 1, ¿cuál de las siguientes afirmaciones es correcta?',
      options: [
        'Se asocia a deficiencia de hipocretina (orexina) en el líquido cefalorraquídeo.',
        'No cursa con cataplejía ni alteraciones del sueño REM.',
        'Es más frecuente en mujeres y se asocia a exceso de serotonina.',
        'No se relaciona con ningún alelo HLA específico.',
      ],
      correct: 1,
      explanation:
        'Narcolepsia tipo 1 = con cataplejía e hipocretina baja en el LCR, por pérdida de neuronas hipotalámicas. Se asocia fuertemente al HLA-DQB1*06:02 y tiene entrada precoz en REM.',
    },
    {
      number: 167,
      kind: 'bloque',
      topicId: 'epilepsia',
      tag: 'Epilepsia · Diagnóstico diferencial',
      stem: 'Respecto al diagnóstico diferencial de las crisis epilépticas, ¿cuál de las siguientes afirmaciones es correcta?',
      options: [
        'Los síncopes neuromediados tienen una fase tónica prolongada.',
        'En las crisis psicógenas el EEG muestra siempre descargas epileptiformes.',
        'La amnesia global transitoria cursa con pérdida de conciencia prolongada.',
        'Los síncopes presentan recuperación rápida sin confusión poscrítica.',
      ],
      correct: 4,
      explanation:
        'El síncope se recupera en segundos y sin confusión. Las crisis psicógenas tienen EEG normal durante el episodio, y en la AGT no se pierde la conciencia.',
    },
    {
      number: 168,
      kind: 'bloque',
      topicId: 'cefalea',
      tag: 'Cefalea · Tensional',
      stem: '¿Cuál de las siguientes características es típica de la cefalea tensional?',
      options: [
        'Dolor pulsátil bilateral con fotofobia.',
        'Dolor pulsátil unilateral.',
        'Dolor opresivo bilateral.',
        'Dolor que empeora con el ejercicio físico.',
      ],
      correct: 3,
      explanation:
        'Opresiva, bilateral, leve-moderada y no empeora con la actividad. Pulsátil, unilateral y que empeora con el ejercicio es migraña.',
    },
    {
      number: 169,
      kind: 'bloque',
      topicId: 'movimiento',
      tag: 'Movimiento · Parkinson',
      stem: '¿Cuál de los siguientes hallazgos apoya el diagnóstico de enfermedad de Parkinson según los criterios de la Movement Disorder Society (MDS)?',
      options: [
        'Ausencia de respuesta al tratamiento con levodopa.',
        'Pérdida de olfato.',
        'Caídas recurrentes en los primeros años.',
        'Disfunción cerebelosa precoz.',
      ],
      correct: 2,
      explanation:
        'La pérdida de olfato es uno de los criterios de apoyo MDS. La falta de respuesta a levodopa y la disfunción cerebelosa son criterios de exclusión, y las caídas precoces una bandera roja.',
    },
    {
      number: 170,
      kind: 'bloque',
      topicId: 'semiologia',
      tag: 'Semiología · Tono',
      stem: 'En la exploración del tono muscular, ¿qué caracteriza a la hipertonía espástica?',
      options: [
        'Aumento de la resistencia constante durante todo el movimiento.',
        'Aumento de la resistencia dependiente de la velocidad del movimiento.',
        'Disminución del tono con ausencia de resistencia.',
        'Resistencia irregular con fenómeno de rueda dentada.',
      ],
      correct: 2,
      explanation:
        'La espasticidad piramidal depende de la velocidad y cede de golpe (navaja). La 1 y la 4 describen rigidez extrapiramidal; la 3, hipotonía.',
    },
    {
      number: 209,
      kind: 'reserva',
      topicId: 'semiologia',
      tag: 'Reserva · Espasticidad',
      stem: 'En un paciente adulto con lesión medular y espasticidad generalizada, ¿cuál de estos fármacos NO utilizaría como tratamiento?',
      options: ['Diazepam.', 'Lacosamida.', 'Tizanidina.', 'Baclofeno.'],
      correct: 2,
      explanation:
        'La lacosamida es un anticrisis bloqueante de canales de sodio, no un antiespástico. Baclofeno, tizanidina y benzodiacepinas sí lo son.',
    },
    {
      number: 210,
      kind: 'reserva',
      topicId: 'neurocirugia',
      tag: 'Reserva · HII',
      stem: 'En relación con el pseudotumor cerebri o hipertensión intracraneal idiopática (HII), ¿cuál es correcta?',
      options: [
        'Es más frecuente en hombres ancianos con IMC bajo.',
        'Se caracteriza por aumento de la presión de apertura del LCR con composición anormal.',
        'Afecta preferentemente a mujeres jóvenes obesas y puede causar pérdida visual.',
        'El tratamiento inicial consiste en corticoides a dosis altas y restricción hídrica estricta.',
      ],
      correct: 3,
      explanation:
        'Mujer joven y obesa, con presión de LCR alta y composición normal. El papiledema mantenido puede dejar pérdida visual. Se trata con pérdida de peso y acetazolamida.',
    },
    {
      number: 15,
      kind: 'frontera',
      topicId: 'neuropatias',
      tag: 'Nefrología · Amiloidosis',
      stem: 'Se muestra la biopsia (IMAGEN 15) de un paciente con una enfermedad sistémica que puede afectar a múltiples órganos. Prestando atención a la posible afectación neurológica, ¿qué hallazgo le parece más probable?',
      imageUrl: 'https://pub-a0af2de03fec4dd2b89a37964efd1716.r2.dev/questions/2026/15.png',
      options: [
        'Hipotensión ortostática sin respuesta cronotrópica adecuada.',
        'Nistagmo horizontal.',
        'Edema de papila.',
        'Debilidad muscular proximal sin alteraciones sensitivas.',
      ],
      correct: 1,
      explanation:
        'La biopsia muestra un glomérulo ocupado por material rosado, amorfo y sin células: amiloide (se confirma con rojo Congo). La amiloidosis afecta al sistema nervioso periférico, sobre todo al autónomo: hipotensión ortostática sin taquicardia compensadora. Nistagmo y papiledema serían del sistema nervioso central; la debilidad proximal pura, de una miopatía.',
    },
    {
      number: 101,
      kind: 'frontera',
      topicId: 'neurocirugia',
      tag: 'ORL · Fístula de LCR',
      stem: 'En un paciente con rinorrea acuosa unilateral y sospecha de fístula de LCR, ¿cuál es una proteína marcadora de LCR?',
      options: ['Albúmina.', 'Prealbúmina.', 'Beta 2 transferrina.', 'Mielina.'],
      correct: 3,
      explanation:
        'La beta-2-transferrina solo está en el LCR (y la perilinfa). Es la prueba que confirma una rinolicuorrea, típica de la fractura de base de cráneo.',
    },
    {
      number: 133,
      kind: 'frontera',
      topicId: 'placa-motora',
      tag: 'Oncología · Miastenia',
      stem: 'Varón de 63 años con miastenia gravis y melanoma estadio IV BRAF V600E con gran carga tumoral. ¿Tratamiento más razonable según riesgo-beneficio?',
      options: ['Pembrolizumab.', 'Nivolumab.', 'Dabrafenib-Trametinib.', 'Nivolumab-Ipilimumab.'],
      correct: 3,
      explanation:
        'Los inhibidores de checkpoint pueden desencadenar una crisis miasténica grave (a veces con miositis y miocarditis). Si hay BRAF mutado, la terapia dirigida evita ese riesgo.',
    },
    {
      number: 196,
      kind: 'frontera',
      topicId: 'coma',
      tag: 'Urgencias · Coma',
      stem: 'Paciente de 23 años encontrado en la calle con bajo nivel de conciencia, bradicardia a 40 lpm, TA 90/60, sin fiebre y pupilas puntiformes. ¿Antídoto más indicado?',
      options: ['Naloxona.', 'Flumazenilo.', 'Atropina.', 'Pralidoxima.'],
      correct: 1,
      explanation:
        'Coma con miosis puntiforme e hipoventilación = opiáceos → naloxona. Pupilas puntiformes en el coma: opiáceos o lesión protuberancial.',
    },
    {
      number: 199,
      kind: 'frontera',
      topicId: 'neurocirugia',
      tag: 'Urgencias · TCE',
      stem: 'Paciente de 76 años inconsciente tras un traumatismo craneal y cervical por caída. Sobre el manejo de la vía aérea, ¿cuál es FALSA?',
      options: [
        'La apertura de la vía aérea mediante tracción mandibular es la maniobra de elección.',
        'Lo prioritario es colocar un collarín cervical rígido.',
        'La apertura de la vía aérea es prioritaria en un paciente con un traumatismo.',
        'Una vez abierta la vía aérea, es recomendable usar un dispositivo orofaríngeo.',
      ],
      correct: 2,
      explanation:
        'La A del ABCDE es la vía aérea con control cervical manual (tracción mandibular). El collarín rígido no va antes que abrir la vía aérea.',
    },
    {
      number: 90,
      kind: 'frontera',
      topicId: 'neurocirugia',
      tag: 'Trauma · Lumbalgia',
      stem: '¿Cuál de las siguientes es una red flag durante la anamnesis y exploración de una lumbalgia?',
      options: [
        'Dolor lumbar de patrón mecánico.',
        'Dolor a la palpación de espinosas.',
        'Antecedentes personales de proceso neoplásico.',
        'Paciente de 45 años.',
      ],
      correct: 3,
      explanation:
        'Un cáncer previo obliga a descartar metástasis vertebral, la causa más frecuente de compresión medular. El dolor mecánico y la edad media no son signos de alarma.',
    },
  ],
  sourcesNote:
    'Pesos calculados con el recuento de preguntas MIR de Neurología y Neurocirugía de 2015 a 2025 y con la clasificación de las preguntas del MIR 2026 (cuaderno oficial, versión 0). Las respuestas del MIR 2026 están contrastadas con las definitivas publicadas tras las impugnaciones (ninguna de estas preguntas fue anulada). La previsión para el MIR 2027 es una media ponderada (70 % los últimos 5 MIR, 30 % los anteriores): orientativa, no una predicción exacta. La extensión de cada tema es aproximada.',
}
