import type { StudyGuide } from '@/types/studyGuide'

// Pesos: preguntas MIR 2015-2025 agrupadas en 16 bloques temáticos propios + clasificación propia del MIR 2026
// (cuaderno oficial, versión 0). Respuestas del 2026 contrastadas con las definitivas publicadas tras las impugnaciones.
export const REUMATOLOGIA_GUIDE: StudyGuide = {
  subjectId: 'reumatologia',
  title: 'Reumatología',
  subtitle: 'Qué estudiar, en qué orden y cuánto pesa cada cosa en el MIR',
  targetExam: 'MIR 2027',
  lastExam: 'MIR 2026',
  historyRange: '2015–2025',
  perYear: [
    { year: 2015, count: 12 },
    { year: 2016, count: 12 },
    { year: 2017, count: 9 },
    { year: 2018, count: 10 },
    { year: 2019, count: 8 },
    { year: 2020, count: 9 },
    { year: 2021, count: 15 },
    { year: 2022, count: 6 },
    { year: 2023, count: 12 },
    { year: 2024, count: 9 },
    { year: 2025, count: 9 },
    { year: 2026, count: 8 },
  ],
  lastExamTotal: 8,
  lastExamReserveTotal: 0,
  topics: [
    {
      id: 'vasculitis',
      code: 'VAS',
      name: 'Vasculitis de pequeño y mediano vaso y Behçet',
      shortName: 'Vasculitis',
      tier: 'imprescindible',
      perYear: [1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2],
      lastExamReserve: 0,
      pages: 17,
      focus:
        'El bloque más fiable de la asignatura: ha caído en los 12 MIR analizados, con 1-2 preguntas cada vez. Casi siempre es un caso clínico que hay que reconocer por su combinación de órganos.',
      hotspots: [
        { name: 'Granulomatosis con poliangeítis y vasculitis ANCA', heat: 3 },
        { name: 'Enfermedad de Behçet: aftas, uveítis, patergia', heat: 3 },
        { name: 'Panarteritis nodosa y vasculitis por IgA', heat: 2 },
        { name: 'Granulomatosis eosinofílica (asma y eosinofilia)', heat: 2 },
        { name: 'Crioglobulinemia, Buerger y pseudovasculitis', heat: 1 },
      ],
      keys: [
        'Piensa en vasculitis ante síntomas generales con afectación de varios órganos a la vez: púrpura palpable, mononeuritis múltiple, glomerulonefritis, hemorragia alveolar.',
        'Granulomatosis con poliangeítis: vía aérea superior (sinusitis costrosa, perforación septal, nariz en silla de montar, estenosis subglótica), nódulos pulmonares que se cavitan y glomerulonefritis. ANCA c anti-PR3.',
        'Poliangeítis microscópica: riñón y pulmón (síndrome renopulmonar) sin granulomas ni vía aérea superior; ANCA p anti-MPO. La granulomatosis eosinofílica añade asma de inicio adulto y eosinofilia, con ANCA positivos solo en menos de la mitad.',
        'Inducción en vasculitis ANCA grave: corticoides a dosis altas con rituximab o ciclofosfamida; después mantenimiento (rituximab o azatioprina).',
        'Panarteritis nodosa: arterias de mediano calibre, sin glomerulonefritis ni ANCA. Mononeuritis, orquitis, dolor abdominal por isquemia, HTA y microaneurismas en la angiografía. Busca siempre el virus de la hepatitis B.',
        'Vasculitis por IgA (Schönlein-Henoch): niño con púrpura palpable en piernas, artralgias, dolor abdominal (a veces invaginación) y hematuria. El pronóstico lo marca el riñón.',
        'Behçet: aftas orales recurrentes obligatorias + úlceras genitales, uveítis (anterior o posterior), eritema nodoso o pseudofoliculitis y patergia positiva. Se asocia a HLA-B51; la afectación ocular grave pide inmunosupresión (anti-TNF).',
        'Crioglobulinemia mixta: púrpura, artralgias, astenia, neuropatía y glomerulonefritis membranoproliferativa con complemento bajo; casi siempre por hepatitis C. Buerger: fumador joven con isquemia distal; dejar de fumar es lo único que funciona.',
      ],
      trap: 'Los ANCA no son de todas las vasculitis: la panarteritis nodosa y la vasculitis por IgA son ANCA negativas. Y el asma orienta a granulomatosis eosinofílica, nunca a poliangeítis microscópica.',
    },
    {
      id: 'espondiloartritis',
      code: 'ESP',
      name: 'Espondiloartritis y artritis psoriásica',
      shortName: 'EspA y APs',
      tier: 'imprescindible',
      perYear: [1, 3, 1, 2, 1, 0, 0, 0, 2, 1, 1, 2],
      lastExamReserve: 0,
      pages: 12,
      focus:
        'Vuelve con fuerza tras tres años sin salir: 6 preguntas de 2023 a 2026, dos de ellas de artritis psoriásica en 2026 (diagnóstico sin psoriasis y elección del tratamiento).',
      hotspots: [
        { name: 'Artritis psoriásica: formas clínicas y tratamiento', heat: 3 },
        { name: 'Espondilitis anquilosante: dolor inflamatorio y radiología', heat: 3 },
        { name: 'Sindesmofitos frente a hiperostosis (Forestier)', heat: 2 },
        { name: 'Tratamiento: ejercicio, AINE y biológicos', heat: 2 },
        { name: 'Artritis reactiva y enteropática', heat: 1 },
      ],
      keys: [
        'Dolor lumbar inflamatorio: empieza antes de los 45 años, de forma insidiosa, mejora con el ejercicio y no con el reposo, despierta en la segunda mitad de la noche y da rigidez matutina larga.',
        'Rasgos comunes de las espondiloartritis: sacroilitis, entesitis (talón), dactilitis, uveítis anterior aguda unilateral, HLA-B27 y factor reumatoide negativo.',
        'Radiología: sacroilitis bilateral y sindesmofitos finos y verticales (columna en caña de bambú). La RM detecta la sacroilitis activa antes que la radiografía. La hiperostosis anquilosante (Forestier) forma puentes gruesos anteriores en ancianos, con discos y sacroilíacas respetados.',
        'Tratamiento axial: ejercicio y AINE a dosis plenas; si no basta, anti-TNF o anti-IL17. El metotrexato y los corticoides orales no sirven para la afectación axial.',
        'Artritis psoriásica: oligoartritis asimétrica, afectación de interfalángicas distales con lesión ungueal, dactilitis, forma axial y artritis mutilante (lápiz en copa). Erosión y neoformación ósea en la misma articulación.',
        'La artritis puede preceder a la psoriasis (en torno a un 15 %): dactilitis, neoformación ósea yuxtaarticular y factor reumatoide negativo bastan para sospecharla. Busca psoriasis oculta (cuero cabelludo, ombligo, pliegue interglúteo) y antecedentes familiares.',
        'Tratamiento de la artritis psoriásica: metotrexato para la periférica; si fracasa, biológicos (anti-TNF, anti-IL17, anti-IL12/23 o anti-IL23). Los inhibidores de JAK se reservan, si no hay alternativa, en mayores de 65 años, fumadores o con riesgo cardiovascular o de cáncer, y se usan con precaución si hay riesgo de trombosis.',
        'Artritis reactiva: oligoartritis asimétrica de piernas 1-4 semanas después de una uretritis o una diarrea; la tríada con conjuntivitis y uretritis es solo una forma de presentación. Los cultivos articulares son estériles.',
      ],
      trap: 'Un HLA-B27 negativo no descarta una espondiloartritis, y la ausencia de lesiones cutáneas no descarta una artritis psoriásica (así cayó en 2026).',
    },
    {
      id: 'lupus',
      code: 'LES',
      name: 'Lupus eritematoso sistémico y síndrome antifosfolípido',
      shortName: 'Lupus y SAF',
      tier: 'imprescindible',
      perYear: [3, 2, 0, 1, 0, 1, 3, 0, 2, 0, 1, 1],
      lastExamReserve: 0,
      pages: 14,
      focus:
        'Muy irregular: años de 3 preguntas y años sin ninguna, pero siempre vuelve. Los autoanticuerpos son la pregunta estrella, y el lupus aparece además en Nefrología, Dermatología y Hematología.',
      hotspots: [
        { name: 'Autoanticuerpos: anti-DNA, anti-Sm, anti-Ro, antihistona', heat: 3 },
        { name: 'Lupus inducido por fármacos', heat: 2 },
        { name: 'Embarazo, lupus neonatal y bloqueo cardiaco', heat: 2 },
        { name: 'Síndrome antifosfolípido: clínica y anticoagulación', heat: 2 },
        { name: 'Nefritis lúpica y tratamiento de base', heat: 2 },
      ],
      keys: [
        'Mujer joven con artritis no erosiva, eritema malar fotosensible, serositis, citopenias o proteinuria: lupus. Los ANA positivos son el requisito de entrada, pero por sí solos no diagnostican (también salen en sanos a título bajo).',
        'Anti-DNA de doble cadena: específicos y siguen la actividad, sobre todo renal (junto con el descenso de C3 y C4). Anti-Sm: los más específicos, pero no varían con la actividad.',
        'Anti-Ro: lupus cutáneo subagudo, síndrome de Sjögren y lupus neonatal (bloqueo auriculoventricular congénito). Anti-RNP: enfermedad mixta del tejido conectivo.',
        'Lupus inducido (hidralazina, procainamida, isoniazida, anti-TNF): artritis y serositis sin afectación renal ni neurológica, anticuerpos antihistona y anti-DNA casi siempre negativos. Se cura retirando el fármaco.',
        'Hidroxicloroquina para todos los pacientes, salvo contraindicación: reduce brotes y trombosis y mejora la supervivencia (control oftalmológico periódico). La nefritis proliferativa se induce con corticoides y micofenolato o ciclofosfamida.',
        'Embarazo: programarlo con la enfermedad inactiva al menos seis meses; mantener la hidroxicloroquina. Los brotes son más probables en el embarazo y el posparto.',
        'Síndrome antifosfolípido: trombosis (arteriales o venosas) o complicaciones obstétricas + anticuerpos persistentes (anticoagulante lúpico, anticardiolipina, anti-β2-glicoproteína I) en dos determinaciones separadas 12 semanas. Tratamiento de la trombosis: acenocumarol o warfarina; los anticoagulantes directos no se recomiendan.',
      ],
      trap: 'El anticoagulante lúpico alarga el TTPA en el laboratorio pero da trombosis, no hemorragias. Y un TTPA alargado sin clínica no siempre es anticoagulante lúpico: en 2026 la respuesta fue un von Willebrand leve.',
    },
    {
      id: 'arteritis',
      code: 'ACG',
      name: 'Arteritis de células gigantes, Takayasu y polimialgia reumática',
      shortName: 'Arteritis y PMR',
      tier: 'alta',
      perYear: [0, 1, 1, 0, 0, 1, 1, 2, 0, 1, 1, 1],
      lastExamReserve: 0,
      pages: 5,
      focus:
        'Pocas páginas y casi una pregunta al año desde 2020: probablemente el bloque más rentable de la asignatura. La polimialgia cayó en 2022 y en 2026.',
      hotspots: [
        { name: 'Arteritis de células gigantes: diagnóstico y tratamiento urgente', heat: 3 },
        { name: 'Polimialgia reumática', heat: 2 },
        { name: 'Afectación de grandes vasos y aorta', heat: 2 },
        { name: 'Ahorradores de corticoides: tocilizumab', heat: 2 },
        { name: 'Arteritis de Takayasu', heat: 1 },
      ],
      keys: [
        'Arteritis de células gigantes: mayor de 50 años con cefalea nueva, arteria temporal engrosada o dolorosa, claudicación mandibular, síntomas visuales y VSG o PCR muy altas. Con reactantes normales el diagnóstico es muy improbable.',
        'La complicación temida es la ceguera por neuropatía óptica isquémica anterior. Ante la sospecha, corticoides en el momento (sin esperar a la biopsia, que sigue siendo válida unos días); con clínica visual, bolos intravenosos de metilprednisolona.',
        'Confirmación: ecografía de temporales (signo del halo) o biopsia; la biopsia puede ser negativa por afectación salteada. El PET o la angio-TC muestran afectación de aorta y ramas en muchos pacientes: vigilar aneurisma de aorta torácica.',
        'Tocilizumab (anti-IL6) reduce recaídas y dosis acumulada de corticoide; el metotrexato es alternativa ahorradora. Añade prevención de osteoporosis (calcio, vitamina D y bifosfonato).',
        'Polimialgia reumática: mayor de 50 años con dolor y rigidez de cinturas escapular y pélvica, VSG alta y factor reumatoide negativo. Respuesta espectacular a prednisona a dosis bajas (12,5-25 mg/día); si no responde, replantea el diagnóstico.',
        'En toda polimialgia pregunta por cefalea, claudicación mandibular y síntomas visuales: si aparecen, es una arteritis y pide dosis altas.',
        'Takayasu: mujer joven con claudicación de brazos, soplos, pulsos asimétricos o ausentes y diferencia de presión entre brazos; afecta a la aorta y sus ramas.',
      ],
      trap: 'Ante sospecha de arteritis de la temporal, tratar primero y biopsiar después. En la polimialgia las dosis de corticoide son bajas; si piden dosis altas, es que hay arteritis.',
    },
    {
      id: 'esclerosis',
      code: 'ESC',
      name: 'Esclerosis sistémica y enfermedad mixta del tejido conectivo',
      shortName: 'Esclerodermia',
      tier: 'alta',
      perYear: [1, 0, 0, 0, 0, 2, 2, 0, 2, 1, 1, 0],
      lastExamReserve: 0,
      pages: 8,
      focus:
        'Casi ausente hasta 2019 y después 8 preguntas de 2020 a 2025: anticuerpos, crisis renal y seguimiento de la afectación visceral. No cayó en 2026.',
      hotspots: [
        { name: 'Anticuerpos: anticentrómero, anti-Scl70, anti-RNA polimerasa III', heat: 3 },
        { name: 'Crisis renal esclerodérmica: IECA y evitar corticoides', heat: 3 },
        { name: 'Cribado de afectación visceral (pulmón, corazón)', heat: 2 },
        { name: 'Raynaud y úlceras digitales', heat: 2 },
        { name: 'Hipertensión pulmonar', heat: 1 },
      ],
      keys: [
        'Raynaud en adulto: pide ANA y capilaroscopia. Con ambos normales es primario; si están alterados (megacapilares, hemorragias, pérdida de capilares), sospecha una enfermedad del tejido conectivo.',
        'Forma limitada: piel dura solo distal a codos y rodillas y en la cara, Raynaud de años, anticentrómero; su complicación típica es la hipertensión pulmonar tardía (incluye el antiguo CREST).',
        'Forma difusa: piel también proximal y tronco, evolución rápida, afectación visceral precoz. Anti-Scl70 (topoisomerasa I) = enfermedad pulmonar intersticial; anti-RNA polimerasa III = crisis renal y afectación cutánea rápida (y más riesgo de cáncer).',
        'Crisis renal esclerodérmica: HTA brusca, fracaso renal y anemia microangiopática, sobre todo en la difusa inicial. Tratamiento con IECA aunque suba la creatinina. Los corticoides a más de 10-15 mg/día la precipitan.',
        'Seguimiento: pruebas de función respiratoria con DLCO y ecocardiograma de forma periódica (anual), además de la presión arterial, para detectar a tiempo la afectación pulmonar e hipertensión pulmonar.',
        'Raynaud grave y úlceras digitales: calcioantagonistas; si no basta, iloprost intravenoso, inhibidores de la fosfodiesterasa 5 o bosentán. Evita betabloqueantes.',
        'Enfermedad mixta del tejido conectivo: mezcla de lupus, esclerodermia y miositis con anti-RNP a título alto; manos hinchadas y Raynaud. Su causa principal de muerte es la hipertensión pulmonar.',
      ],
      trap: 'En la crisis renal esclerodérmica no se suspende el IECA aunque empeore la creatinina, y los corticoides a dosis altas son un factor desencadenante, no un tratamiento.',
    },
    {
      id: 'miopatias',
      code: 'MIO',
      name: 'Miopatías inflamatorias',
      shortName: 'Miopatías',
      tier: 'alta',
      perYear: [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 0],
      lastExamReserve: 0,
      pages: 4,
      focus:
        'Seis años seguidos con pregunta (2020-2025) y solo 4 páginas: tema en alza. Casi siempre preguntan qué anticuerpo va con qué cuadro. No cayó en 2026.',
      hotspots: [
        { name: 'Anticuerpos específicos: anti-MDA5, anti-Jo1, anti-Mi2, anti-TIF1γ', heat: 3 },
        { name: 'Lesiones cutáneas de la dermatomiositis', heat: 2 },
        { name: 'Miopatía necrosante por estatinas (anti-HMGCR)', heat: 2 },
        { name: 'Miositis por cuerpos de inclusión', heat: 1 },
        { name: 'Cribado de neoplasia', heat: 1 },
      ],
      keys: [
        'Debilidad simétrica proximal (subir escaleras, peinarse) con CK elevada: piensa en miopatía inflamatoria. Confirman la RM, el electromiograma y la biopsia; los anticuerpos orientan el subtipo y el pronóstico.',
        'Dermatomiositis: pápulas de Gottron en nudillos, eritema en heliotropo, signo del chal y de la V, manos de mecánico. En el adulto, busca un cáncer (sobre todo con anti-TIF1γ o anti-NXP2).',
        'Anti-Jo1 (síndrome antisintetasa): miositis, enfermedad pulmonar intersticial, artritis, Raynaud, fiebre y manos de mecánico.',
        'Anti-MDA5: dermatomiositis con poca o ninguna miositis, úlceras cutáneas y enfermedad intersticial rápidamente progresiva, de mal pronóstico. Anti-Mi2: dermatomiositis clásica, muy cutánea y con buena respuesta al tratamiento.',
        'Miopatía necrosante inmunomediada: CK muy alta, poca inflamación en la biopsia; anti-HMGCR (tras estatinas, y no mejora al retirarlas) o anti-SRP.',
        'Miositis por cuerpos de inclusión: varón mayor de 50 años, debilidad asimétrica y distal (flexores de los dedos, cuádriceps), CK normal o poco elevada y mala respuesta a corticoides.',
        'Tratamiento: corticoides a dosis altas con un ahorrador (metotrexato, azatioprina o micofenolato); inmunoglobulinas en casos graves o refractarios.',
      ],
      trap: 'La miositis por cuerpos de inclusión no responde a corticoides y da debilidad distal. Si el enunciado habla de estatinas y la debilidad sigue tras retirarlas, piensa en anti-HMGCR.',
    },
    {
      id: 'osea',
      code: 'OST',
      name: 'Osteoporosis, osteomalacia y enfermedad de Paget',
      shortName: 'Metabólica ósea',
      tier: 'alta',
      perYear: [0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 0],
      lastExamReserve: 0,
      pages: 10,
      focus:
        'Nueve años seguidos con una pregunta (2016-2024), casi siempre de osteoporosis y de sus fármacos. Lleva dos años sin salir: candidato claro a volver en 2027.',
      hotspots: [
        { name: 'Osteoporosis: densitometría y a quién tratar', heat: 3 },
        { name: 'Fármacos: bifosfonatos, denosumab, teriparatida y efectos adversos', heat: 3 },
        { name: 'Calcio y vitamina D: cuándo sirven', heat: 2 },
        { name: 'Enfermedad de Paget', heat: 1 },
        { name: 'Osteomalacia', heat: 1 },
      ],
      keys: [
        'Densitometría (DXA) en columna lumbar y cadera: osteoporosis con T-score ≤ -2,5. Una fractura por fragilidad (vértebra, cadera) basta para tratar, sea cual sea la densitometría.',
        'La radiografía sirve para detectar fracturas, no para medir la densidad. Antes de tratar, descarta causas secundarias (corticoides, hipogonadismo, hiperparatiroidismo, hipertiroidismo, celiaquía, mieloma).',
        'Bifosfonatos de primera línea. Orales en ayunas, con agua, de pie 30 minutos; evitarlos si el filtrado es menor de 30-35 ml/min y corregir antes una hipocalcemia. Riesgos raros con uso prolongado: osteonecrosis de mandíbula y fractura atípica de fémur.',
        'Denosumab (anti-RANKL, subcutáneo cada 6 meses): sirve en insuficiencia renal; si se suspende hay efecto rebote con fracturas vertebrales, así que hay que pasar a un bifosfonato. Teriparatida (osteoformador): osteoporosis grave con fracturas; no en Paget ni en quien ha recibido radioterapia ósea.',
        'Calcio y vitamina D son el soporte de cualquier tratamiento, pero por sí solos no evitan fracturas.',
        'Paget: anciano con dolor óseo o deformidad, fosfatasa alcalina elevada con calcio y fósforo normales, huesos engrosados en la radiografía (cráneo, pelvis, tibia en sable). Complicaciones: sordera, compresiones nerviosas, insuficiencia cardiaca de gasto alto y osteosarcoma. Tratamiento: zoledronato.',
        'Osteomalacia: mineralización defectuosa, casi siempre por déficit de vitamina D. Dolor óseo difuso y debilidad proximal, fosfatasa alcalina alta, calcio y fósforo bajos, PTH alta y pseudofracturas de Looser-Milkman.',
      ],
      trap: 'Un paciente con fractura por fragilidad se trata aunque la densitometría no llegue a -2,5, y el calcio con vitamina D solos no cuentan como tratamiento antiosteoporótico.',
    },
    {
      id: 'cristales',
      code: 'GOT',
      name: 'Gota y otras artritis por microcristales',
      shortName: 'Microcristales',
      tier: 'alta',
      perYear: [1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1],
      lastExamReserve: 0,
      pages: 8,
      focus:
        'Una pregunta cada uno o dos años, casi siempre del tratamiento de la gota. En 2026 preguntaron cuándo empezar el alopurinol.',
      hotspots: [
        { name: 'Tratamiento de la crisis y de la hiperuricemia', heat: 3 },
        { name: 'Diagnóstico por artrocentesis y diferencia con la séptica', heat: 2 },
        { name: 'Condrocalcinosis (pirofosfato cálcico)', heat: 2 },
        { name: 'Hiperuricemia asintomática y fármacos que la suben', heat: 1 },
      ],
      keys: [
        'Diagnóstico de certeza: cristales de urato en el líquido sinovial (agujas con birrefringencia negativa). Ante una monoartritis aguda, artrocentesis: una séptica puede coexistir y la uricemia puede ser normal en plena crisis.',
        'Crisis: colchicina, AINE o corticoides (orales o intraarticulares), según las comorbilidades. Si el paciente ya toma alopurinol, no se retira.',
        'Hipouricemiante (alopurinol primero, febuxostat como alternativa) si hay crisis recurrentes, tofos, artropatía, litiasis úrica o insuficiencia renal. Empieza a dosis bajas y sube hasta una uricemia menor de 6 mg/dl (menor de 5 si hay tofos).',
        'Al empezar el hipouricemiante, profilaxis de crisis con colchicina a dosis bajas unos meses: al bajar el urato se movilizan cristales.',
        'La hiperuricemia asintomática no se trata. Suben el ácido úrico las tiazidas y los diuréticos de asa, el AAS a dosis bajas, la ciclosporina, la pirazinamida y el etambutol; el losartán y el fenofibrato lo bajan un poco.',
        'Condrocalcinosis: anciano, rodilla o muñeca, cristales romboidales con birrefringencia débilmente positiva y calcificación lineal del cartílago (rodilla, ligamento triangular del carpo, sínfisis del pubis). En jóvenes, descarta hemocromatosis, hiperparatiroidismo e hipomagnesemia.',
      ],
      trap: 'No se empieza el alopurinol en plena crisis (tradicionalmente) ni se retira si ya lo tomaba; y tratar solo las crisis en una gota recurrente es insuficiente.',
    },
    {
      id: 'ar',
      code: 'AR',
      name: 'Artritis reumatoide',
      shortName: 'A. reumatoide',
      tier: 'media',
      perYear: [3, 1, 0, 1, 1, 0, 2, 0, 0, 1, 0, 0],
      lastExamReserve: 0,
      pages: 10,
      focus:
        'Fue de los temas fuertes (3 preguntas en 2015), pero solo ha salido una vez desde 2022. Tema clásico y asequible: repasa extraarticulares y tratamiento.',
      hotspots: [
        { name: 'Manifestaciones extraarticulares y complicaciones', heat: 2 },
        { name: 'Tratamiento por objetivos: metotrexato y biológicos', heat: 2 },
        { name: 'Cribado de tuberculosis antes de biológicos o JAK', heat: 1 },
        { name: 'Factores de mal pronóstico', heat: 1 },
      ],
      keys: [
        'Poliartritis simétrica de pequeñas articulaciones de manos y pies (MCF, IFP, MTF) con rigidez matutina de más de una hora. Respeta las interfalángicas distales y la columna salvo la cervical (subluxación atloaxoidea).',
        'Factor reumatoide y anti-CCP: los anti-CCP son más específicos y predicen erosiones. Radiografía: osteopenia yuxtaarticular y erosiones marginales, sin formación de hueso nuevo.',
        'Extraarticulares: nódulos reumatoides, enfermedad pulmonar intersticial, epiescleritis y escleritis (no uveítis), síndrome de Felty (esplenomegalia y neutropenia), vasculitis reumatoide y amiloidosis secundaria (proteinuria). La anemia más frecuente es la de trastorno crónico.',
        'Más riesgo cardiovascular y de linfoma. La enfermedad activa y mantenida es la que más lo sube.',
        'Tratamiento por objetivos (remisión o baja actividad), con revisiones frecuentes: metotrexato de primera elección (con ácido fólico), corticoides a dosis bajas como puente. Si no se alcanza el objetivo: biológico (anti-TNF, abatacept, tocilizumab, rituximab) o inhibidor de JAK.',
        'Antes de biológicos o inhibidores de JAK: descartar tuberculosis latente (Mantoux o IGRA y radiografía de tórax) y hepatitis B y C; vacunar.',
        'Mal pronóstico: anti-CCP o factor reumatoide a título alto, erosiones precoces, muchas articulaciones, reactantes altos y extraarticulares.',
      ],
      trap: 'La uveítis no es propia de la artritis reumatoide (lo es la escleritis), y las erosiones sin formación de hueso nuevo la separan de la artritis psoriásica.',
    },
    {
      id: 'otras',
      code: 'OTR',
      name: 'Fibromialgia, enfermedad por IgG4, inmunoterapia y otras',
      shortName: 'IgG4 y otras',
      tier: 'media',
      perYear: [0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1],
      lastExamReserve: 0,
      pages: 3,
      focus:
        'Cajón de temas cortos con una pregunta cada pocos años. En 2026 entró uno nuevo: la artritis por inhibidores de puntos de control.',
      hotspots: [
        { name: 'Enfermedad relacionada con IgG4', heat: 2 },
        { name: 'Fibromialgia', heat: 2 },
        { name: 'Efectos reumáticos de la inmunoterapia (anti-PD-1)', heat: 2 },
        { name: 'Policondritis, Charcot, osteoartropatía hipertrófica', heat: 1 },
      ],
      keys: [
        'Enfermedad relacionada con IgG4: lesiones pseudotumorales en uno o varios órganos (páncreas autoinmune, colangitis, glándulas salivales y lagrimales, fibrosis retroperitoneal, periaortitis). Biopsia: infiltrado linfoplasmocitario rico en células IgG4, fibrosis estoriforme (en remolino) y flebitis obliterante. Responde a corticoides.',
        'Fibromialgia: dolor difuso crónico con fatiga, sueño no reparador y alteraciones cognitivas, sin inflamación y con analítica normal. Tratamiento: educación y ejercicio aeróbico gradual; fármacos de apoyo como amitriptilina, duloxetina o pregabalina. Evita opioides mayores.',
        'Inhibidores de puntos de control (anti-PD-1, anti-PD-L1, anti-CTLA-4): pueden causar artritis inflamatoria, cuadros tipo polimialgia, síndrome seco o miositis, casi siempre seronegativos. En los leves: AINE o corticoides a dosis bajas sin retirar la inmunoterapia, de acuerdo con Oncología.',
        'Policondritis recidivante: inflamación de cartílagos (pabellón auricular respetando el lóbulo, nariz, tráquea), con riesgo de colapso de la vía aérea.',
        'Artropatía de Charcot: articulación muy destruida y poco dolorosa por neuropatía (diabetes en el pie, siringomielia en el hombro, tabes en la rodilla).',
      ],
      trap: 'En la fibromialgia la exploración y la analítica son normales: unos reactantes altos obligan a buscar otra cosa. Y unos ANA 1/80 tras inmunoterapia no convierten el cuadro en un lupus.',
    },
    {
      id: 'sjogren',
      code: 'SJO',
      name: 'Síndrome de Sjögren',
      shortName: 'Sjögren',
      tier: 'media',
      perYear: [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
      lastExamReserve: 0,
      pages: 2,
      focus:
        'Solo 2 páginas y tres años seguidos con pregunta (2022-2024), siempre alrededor del riesgo de linfoma. Muy rentable.',
      hotspots: [
        { name: 'Factores de riesgo de linfoma', heat: 3 },
        { name: 'Clínica seca y anticuerpos anti-Ro y anti-La', heat: 2 },
        { name: 'Afectación extraglandular', heat: 1 },
      ],
      keys: [
        'Mujer de mediana edad con sequedad ocular y bucal y aumento de las parótidas. Anti-Ro y anti-La, factor reumatoide positivo e hipergammaglobulinemia; test de Schirmer y biopsia de glándula salival menor (infiltrado linfocitario focal).',
        'Riesgo de linfoma muy aumentado (sobre todo MALT, después difuso de células B grandes). Lo predicen: parótidas persistentemente aumentadas, púrpura, complemento bajo (C4), crioglobulinemia, componente monoclonal y linfopenia.',
        'Extraglandular: artritis no erosiva, Raynaud, acidosis tubular renal distal, nefritis intersticial, neuropatía, pulmón.',
        'Anti-Ro en la embarazada: riesgo de lupus neonatal y bloqueo cardiaco congénito, aunque la madre tenga pocos síntomas.',
        'Tratamiento sintomático (lágrimas artificiales, pilocarpina); inmunosupresión solo si hay afectación extraglandular.',
      ],
      trap: 'Parótida que crece de forma persistente o aparición de crioglobulinas y C4 bajo en un Sjögren: piensa en linfoma.',
    },
    {
      id: 'autoinflamatorias',
      code: 'AUT',
      name: 'Enfermedades autoinflamatorias y amiloidosis',
      shortName: 'Autoinflamación',
      tier: 'media',
      perYear: [0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0],
      lastExamReserve: 0,
      pages: 6,
      focus:
        'Una pregunta cada dos años aproximadamente. La fiebre mediterránea familiar es la que más sale; la amiloidosis aparece también en Nefrología (imagen 15 de 2026).',
      hotspots: [
        { name: 'Fiebre mediterránea familiar', heat: 2 },
        { name: 'Amiloidosis AL y AA: clínica y diagnóstico', heat: 2 },
        { name: 'VEXAS y otras autoinflamatorias', heat: 1 },
      ],
      keys: [
        'Autoinflamatorias: brotes de fiebre e inflamación sin autoanticuerpos ni linfocitos T autorreactivos; falla la inmunidad innata (inflamasoma, IL-1).',
        'Fiebre mediterránea familiar: herencia autosómica recesiva, gen MEFV. Episodios de 1-3 días de fiebre con serositis (dolor abdominal, torácico) y artritis. Colchicina de por vida: controla los brotes y previene la amiloidosis AA.',
        'Amiloidosis AL (cadenas ligeras, discrasia de células plasmáticas): síndrome nefrótico, miocardiopatía restrictiva, neuropatía periférica y autonómica (hipotensión ortostática), macroglosia, púrpura periorbitaria.',
        'Amiloidosis AA: secundaria a inflamación crónica (artritis reumatoide, fiebre mediterránea, EII, infecciones crónicas); casi siempre empieza por el riñón (proteinuria).',
        'Diagnóstico: biopsia de grasa abdominal (o del órgano afectado) con rojo Congo: birrefringencia verde manzana con luz polarizada. Tipificar siempre la proteína.',
        'VEXAS: varón mayor con fiebre, condritis, vasculitis, lesiones cutáneas y anemia macrocítica; mutación somática de UBA1.',
      ],
    },
    {
      id: 'septica',
      code: 'SEP',
      name: 'Artritis sépticas',
      shortName: 'A. séptica',
      tier: 'media',
      perYear: [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
      lastExamReserve: 0,
      pages: 6,
      focus:
        'Cinco años seguidos con pregunta (2015-2019) y ninguna desde entonces. Estúdiala con la gota: comparten el enfoque de la monoartritis aguda.',
      hotspots: [
        { name: 'Manejo de la monoartritis séptica', heat: 2 },
        { name: 'Microorganismo según edad y factores de riesgo', heat: 2 },
        { name: 'Artritis víricas y gonocócica', heat: 1 },
      ],
      keys: [
        'Monoartritis aguda: artrocentesis siempre. Líquido séptico: turbio, más de 50.000 leucocitos con predominio de neutrófilos, glucosa baja; Gram y cultivo. Hemocultivos antes del antibiótico.',
        'Antibiótico intravenoso empírico en cuanto se extraen los cultivos y drenaje articular (artrocentesis repetidas, artroscopia o artrotomía). La cadera y los casos que no mejoran se drenan en quirófano.',
        'Staphylococcus aureus es el germen más frecuente; en jóvenes sexualmente activos, gonococo; en usuarios de drogas intravenosas, bacilos gramnegativos (Pseudomonas) y articulaciones axiales (esternoclavicular, sacroilíaca); en prótesis precoces, estafilococos.',
        'Infección gonocócica diseminada: poliartralgias migratorias, tenosinovitis y pústulas cutáneas; los cultivos articulares suelen ser negativos. Ceftriaxona.',
        'Las víricas (parvovirus B19, rubéola, hepatitis B) son la causa más frecuente de poliartritis aguda: simétricas y autolimitadas.',
      ],
      trap: 'Una monoartritis con fiebre no se trata como gota sin puncionar: se puncionan todas, y el antibiótico no espera al resultado del cultivo.',
    },
    {
      id: 'artrosis',
      code: 'ART',
      name: 'Artrosis',
      shortName: 'Artrosis',
      tier: 'baja',
      perYear: [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      lastExamReserve: 0,
      pages: 4,
      focus: 'Una pregunta al año entre 2015 y 2017 y ninguna desde entonces. Basta con el patrón clínico y radiológico.',
      hotspots: [
        { name: 'Clínica y radiología de la artrosis', heat: 1 },
        { name: 'Tratamiento escalonado', heat: 1 },
      ],
      keys: [
        'Dolor mecánico que empeora con el uso y mejora con el reposo, rigidez breve (menos de 30 minutos) tras la inactividad, crepitación. Reactantes normales.',
        'Radiografía: pinzamiento asimétrico del espacio articular, osteofitos, esclerosis y quistes subcondrales. Afecta a interfalángicas distales (Heberden) y proximales (Bouchard), base del pulgar, rodilla, cadera y columna; respeta MCF, muñecas y hombros.',
        'Tratamiento: pérdida de peso y ejercicio, paracetamol o AINE tópicos u orales, infiltración de corticoides en brotes; prótesis si el dolor es refractario.',
      ],
    },
    {
      id: 'introduccion',
      code: 'LIQ',
      name: 'Introducción: líquido sinovial y pruebas en reumatología',
      shortName: 'Introducción',
      tier: 'baja',
      perYear: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
      lastExamReserve: 0,
      pages: 6,
      focus: 'Casi nunca se pregunta por sí sola, pero el líquido sinovial y los autoanticuerpos son la base para resolver casos de otros temas.',
      hotspots: [
        { name: 'Tipos de líquido sinovial', heat: 2 },
        { name: 'Mapa de autoanticuerpos', heat: 1 },
      ],
      keys: [
        'Líquido mecánico: claro, viscoso, menos de 2.000 leucocitos (artrosis). Inflamatorio: turbio, 2.000-50.000, glucosa algo baja (artritis reumatoide, cristales). Séptico: purulento, más de 50.000 con neutrófilos y glucosa muy baja. Hemático: traumatismo, hemofilia, sinovitis villonodular.',
        'La artrocentesis es la primera prueba ante una monoartritis aguda: distingue cristales e infección.',
        'Mapa rápido de anticuerpos: anti-CCP (artritis reumatoide), anti-DNA y anti-Sm (lupus), antihistona (lupus inducido), anti-Ro y anti-La (Sjögren, lupus neonatal), anticentrómero y anti-Scl70 (esclerosis sistémica), anti-RNP (enfermedad mixta), anti-Jo1 y anti-MDA5 (miopatías).',
      ],
    },
    {
      id: 'still',
      code: 'STL',
      name: 'Enfermedad de Still y artritis idiopática juvenil',
      shortName: 'Still y AIJ',
      tier: 'baja',
      perYear: [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      lastExamReserve: 0,
      pages: 4,
      focus: 'Una sola pregunta en 2017. Quédate con el cuadro típico del Still del adulto.',
      hotspots: [
        { name: 'Still del adulto: fiebre, exantema y ferritina', heat: 1 },
        { name: 'Artritis idiopática juvenil y uveítis', heat: 1 },
      ],
      keys: [
        'Still del adulto: fiebre alta en picos, exantema asalmonado evanescente que aparece con la fiebre, artritis, odinofagia, leucocitosis con neutrofilia y ferritina muy elevada, con ANA y factor reumatoide negativos. Es un diagnóstico de exclusión (infecciones, linfoma).',
        'Complicación grave: síndrome de activación macrofágica. Tratamiento con corticoides y, si no basta, anti-IL1 (anakinra) o anti-IL6.',
        'Artritis idiopática juvenil oligoarticular: niña pequeña con ANA positivos y uveítis anterior crónica asintomática: revisiones oftalmológicas periódicas con lámpara de hendidura.',
      ],
    },
  ],
  insights: [
    {
      icon: 'trending_down',
      title: 'Un año flojo en número',
      body: 'El MIR 2026 trajo 8 preguntas de Reumatología, sin reservas ni imágenes: por debajo de la media de 10 desde 2015. Seis vinieron en el bloque 179-184 y dos sueltas (Behçet y polimialgia).',
    },
    {
      icon: 'medication',
      title: 'El tratamiento, protagonista',
      body: 'Dos preguntas fueron de tratamiento puro (cuándo empezar el alopurinol y qué fármaco evitar en un paciente de alto riesgo cardiovascular: los inhibidores de JAK) y otra, de reconocer una artritis causada por la inmunoterapia del cáncer.',
    },
    {
      icon: 'trending_up',
      title: 'Lo que sube',
      body: 'Arteritis de células gigantes y polimialgia (9 preguntas desde 2015, contando la de 2026, en solo 5 páginas), miopatías inflamatorias (al menos una pregunta al año de 2020 a 2025) y Sjögren (tres años seguidos). Son los temas con mejor rendimiento por página.',
    },
    {
      icon: 'event_busy',
      title: 'Lo que falta y puede volver',
      body: 'Osteoporosis cayó nueve años seguidos y lleva dos sin salir; esclerosis sistémica y miopatías no salieron en 2026. Artritis reumatoide solo ha salido una vez desde 2022.',
    },
    {
      icon: 'vaccines',
      title: 'Inmunoterapia y JAK: temas nuevos',
      body: 'Dos preguntas de 2026 se basan en novedades terapéuticas: la seguridad de los inhibidores de JAK tras ORAL Surveillance y los efectos adversos reumáticos de los anti-PD-1. Conviene repasar los fármacos nuevos, no solo las enfermedades.',
    },
    {
      icon: 'hub',
      title: 'Reumatología también en otras asignaturas',
      body: 'Anemia en un lupus (Hematología, anulada), TTPA alargado antes de una prótesis (Hematología), Kawasaki (Pediatría), amiloidosis con disautonomía (Nefrología, con imagen) y banderas rojas de la lumbalgia (Trauma).',
    },
  ],
  plan: [
    {
      title: '1.ª vuelta · Los pilares',
      subtitle: 'Casi la mitad de las preguntas: vasculitis, espondiloartritis y lupus, más la arteritis de la temporal y la polimialgia, cortas y muy rentables.',
      topicIds: ['vasculitis', 'arteritis', 'espondiloartritis', 'lupus'],
      days: 4,
    },
    {
      title: '2.ª vuelta · Temas que rotan',
      subtitle: 'Salen casi todos los años por turnos: esclerodermia, miopatías, osteoporosis, gota y artritis reumatoide.',
      topicIds: ['esclerosis', 'miopatias', 'osea', 'cristales', 'ar'],
      days: 4,
    },
    {
      title: '3.ª vuelta · Pasada rápida',
      subtitle: 'Esquemas y tablas: Sjögren, IgG4 y fibromialgia, autoinflamatorias, artritis séptica y lo básico de artrosis, líquido sinovial y Still.',
      topicIds: ['sjogren', 'otras', 'autoinflamatorias', 'septica', 'artrosis', 'introduccion', 'still'],
      days: 2,
    },
  ],
  questions: [
    {
      number: 135,
      kind: 'bloque',
      topicId: 'vasculitis',
      tag: 'Vasculitis · Behçet',
      stem: 'Acude a urgencias un varón de 25 años con una uveítis anterior izquierda. En su historial clínico únicamente destaca que ha tenido úlceras orales dolorosas con cierta frecuencia en los últimos dos años. Refiere la aparición de una pápula eritematosa alrededor del sitio de punción de la vacuna antigripal, que recibió recientemente. ¿Cuál es el diagnóstico más probable?',
      options: [
        'Sarcoidosis.',
        'Sífilis.',
        'Enfermedad de Behçet.',
        'Enfermedad de Crohn.',
      ],
      correct: 3,
      explanation:
        'Aftas orales recurrentes, uveítis anterior y patergia (pápula donde se pinchó la vacuna) en un varón joven: enfermedad de Behçet. La sarcoidosis y la sífilis no dan aftas recurrentes ni patergia, y el Crohn tendría clínica digestiva.',
    },
    {
      number: 136,
      kind: 'bloque',
      topicId: 'arteritis',
      tag: 'Arteritis y PMR · Polimialgia',
      stem: 'Acude a su consulta un varón de 70 años con rigidez matutina y dolor a la movilización de cintura escapular y pélvica bilateral, desde hace tres meses, sin afectación de otras articulaciones periféricas. En la analítica destacan una leve anemia normocítica normocrómica y una velocidad de sedimentación glomerular de 85 mm en la primera hora. El factor reumatoide y los anticuerpos antipeptídicos citrulinados son negativos. ¿Cuál es su diagnóstico?',
      options: [
        'Artritis reumatoide seronegativa.',
        'Polimialgia reumática.',
        'Artritis indiferenciada.',
        'Artrosis.',
      ],
      correct: 2,
      explanation:
        'Mayor de 50 años con dolor y rigidez de cinturas, sin sinovitis periférica, VSG alta y FR/anti-CCP negativos: polimialgia reumática (el enunciado dice "glomerular" por "globular"). Prednisona a dosis bajas y preguntar por síntomas de arteritis de la temporal.',
    },
    {
      number: 179,
      kind: 'bloque',
      topicId: 'espondiloartritis',
      tag: 'EspA · Tratamiento de la APs',
      stem: 'Hombre de 60 años con antecedentes personales de fumador de 30 paq/año, hipertensión arterial, dislipemia, hígado graso. Tratamiento con enalapril, simvastatina y 100 mg de ácido acetilsalicílico por ictus hace 5 años. Tiene una artritis psoriásica a tratamiento con metotrexato a dosis de 25 mg/semana a pesar de lo cual presenta mal control de la actividad y precisa cambio de tratamiento. ¿Cuál considera que NO es la mejor opción de tratamiento?',
      options: [
        'Biológico con mecanismo de acción anti-TNF (Factor de Necrosis Tumoral).',
        'Sintético con diana específica inhibidor de JAK.',
        'Biológico con mecanismo de acción anti-IL17.',
        'Biológico con mecanismo de acción anti-IL12/23.',
      ],
      correct: 2,
      explanation:
        'Fumador de 60 años con HTA, dislipemia e ictus previo: los inhibidores de JAK deben evitarse si hay alternativa (más eventos cardiovasculares, trombosis y cáncer en pacientes de riesgo). Anti-TNF, anti-IL17 y anti-IL12/23 son opciones válidas tras fallar el metotrexato.',
    },
    {
      number: 180,
      kind: 'bloque',
      topicId: 'otras',
      tag: 'Otras · Inmunoterapia',
      stem: 'Varón de 58 años, sin antecedentes personales ni toma de fármacos que tras un control anual de empresa es diagnosticado de carcinoma renal por lo que se inicia tratamiento con Pembrolizumab (anti PD1). Acude a S de Reumatología por un cuadro de poliartritis, predominantemente rizomiélica, de 2 meses de evolución con marcada elevación de reactantes de fase aguda. El análisis de orina, el hemograma y la bioquímica son normales. El factor reumatoide y los anti péptido cíclico citrulinado son negativos. Los ANA positivos a títulos de 1/80 patrón homogéneo ¿Cuál de los siguientes diagnósticos sería el más probable?',
      options: [
        'Vasculitis secundaria al carcinoma.',
        'Síndrome paraneoplásico.',
        'Enfermedad reumática secundaria al Pembrolizumab.',
        'Lupus eritematoso sistémico.',
      ],
      correct: 3,
      explanation:
        'Poliartritis rizomélica seronegativa con reactantes altos tras empezar pembrolizumab: efecto adverso inmunomediado del anti-PD-1. Unos ANA 1/80 son inespecíficos; nada apunta a lupus ni a vasculitis.',
    },
    {
      number: 181,
      kind: 'bloque',
      topicId: 'cristales',
      tag: 'Microcristales · Gota',
      stem: 'Paciente de 55 años que acude por cuadro de monoartritis aguda autolimitada de primera metatarsofalángica. Refiere episodios repetidos en los últimos 3 años que trató con analgésicos. Aporta analítica con uricemia de 11 mg/dl. Resto de estudios normales. ¿Cuál sería el tratamiento más indicado para el paciente?',
      options: [
        'Colchicina y antiinflamatorios durante la crisis y luego suspender ambos.',
        'Colchicina y antiinflamatorios y cuando esté asintomático suspender antiinflamatorios y añadir alopurinol.',
        'Alopurinol y antiinflamatorios durante la crisis y después suspender ambos.',
        'Colchicina y antiinflamatorios durante la crisis y después suspender antiinflamatorios y mantener colchicina.',
      ],
      correct: 2,
      explanation:
        'Gota con crisis repetidas y urato de 11: tratar la crisis con colchicina y AINE y, ya asintomático, añadir alopurinol (objetivo <6 mg/dl) manteniendo la colchicina unos meses como profilaxis.',
    },
    {
      number: 182,
      kind: 'bloque',
      topicId: 'lupus',
      tag: 'Lupus · Autoanticuerpos',
      stem: '¿Cuál de las siguientes afirmaciones sobre los anticuerpos antinucleares es correcta?',
      options: [
        'Los pacientes con lupus inducido por fármacos suelen tener anticuerpos antihistonas y anti-DNA de doble cadena positivos.',
        'Los anticuerpos anti-DNA de cadena única son específicos del lupus eritematoso sistémico.',
        'El título de anticuerpos anti-DNA de doble cadena suele guardar correlación con la actividad de la glomérulo nefritis lúpica.',
        'La positividad de anticuerpos anti-Sm orienta hacia el diagnostico de lupus inducido por fármacos.',
      ],
      correct: 3,
      explanation:
        'El título de anti-DNA de doble cadena sigue la actividad de la nefritis lúpica. El lupus inducido tiene antihistona con anti-DNA negativos; los anti-DNA de cadena simple son inespecíficos y los anti-Sm, específicos del lupus sistémico.',
    },
    {
      number: 183,
      kind: 'bloque',
      topicId: 'espondiloartritis',
      tag: 'EspA · Artritis psoriásica',
      stem: 'Una mujer de 50 años acude a consulta por dolor lumbar inflamatorio. La exploración denota limitación de la movilidad lumbar y tumefacción global del segundo y tercero dedo de pie derecho y cuarto dedo de pie izquierdo. No tiene lesiones cutáneas. La analítica demuestra elevación de reactantes de fase aguda. El Factor reumatoide (FR) y los anticuerpos contra péptido cíclico citrulinado (ACPA) son negativos. Los anticuerpos antinucleares (ANA) y el HLA-B27 también son negativos. Los estudios de imagen de ambos pies evidencian la presencia de erosión junto a neoformación ósea yuxta-articular. ¿Cuál sería su diagnóstico?',
      options: [
        'Artritis reumatoide.',
        'Enfermedad mixta del tejido conectivo.',
        'Sarcoidosis.',
        'Artritis psoriásica.',
      ],
      correct: 4,
      explanation:
        'Dolor lumbar inflamatorio, dactilitis y erosiones con neoformación ósea yuxtaarticular, seronegativa: artritis psoriásica aunque aún no haya psoriasis. HLA-B27 negativo no la descarta; la AR erosiona sin formar hueso.',
    },
    {
      number: 184,
      kind: 'bloque',
      topicId: 'vasculitis',
      tag: 'Vasculitis · ANCA',
      stem: '¿Cuál de estas afirmaciones es correcta sobre las vasculitis pulmonares?',
      options: [
        'La granulomatosis eosinofílica con poliangitis (GEPA) tiene autoanticuerpos ANCA anti-PR3 elevados en el 80% de los casos.',
        'La enfermedad anti-membrana basal glomerular comienza siempre con afectación pulmonar seguida en ocasiones de una afectación renal leve.',
        'Poliangitis microscópica cursa como una forma de asma grave con escasa participación renal.',
        'La granulomatosis con poliangitis (GPA) afecta frecuentemente a la vía aérea superior.',
      ],
      correct: 4,
      explanation:
        'La granulomatosis con poliangeítis afecta casi siempre a la vía aérea superior. La eosinofílica tiene ANCA en menos de la mitad (anti-MPO), el asma es suyo y no de la poliangeítis microscópica, y la anti-MBG puede ser solo renal.',
    },
    {
      number: 139,
      kind: 'frontera',
      topicId: 'lupus',
      tag: 'Hematología · Anulada',
      stem: 'Mujer de 55 años diagnosticada de lupus eritematoso sistémico. Consulta por astenia en los últimos tres meses. En la analítica destacan eritrocitos: 3x10¹²/L, Hemoglobina: 9,1 g/dL, volumen corpuscular medio: 81 fL, reticulocitos: 250x10⁹/L, leucocitos: 7.2x10⁹/L, plaquetas: 230x10⁹/L. Sideremia: 25 mcg/dL, saturación de transferrina: 19%. Ferritina: 400 ng/mL ¿Qué tipo de anemia tiene esta paciente?',
      options: [
        'Anemia inflamatoria crónica.',
        'Anemia ferropénica.',
        'Anemia hemolítica.',
        'Talasemia menor.',
      ],
      correct: 1,
      explanation:
        'ANULADA. Lupus con anemia de VCM en el límite bajo, ferritina alta y sideremia baja: la oficial era la 1 (anemia de la inflamación). Pero los reticulocitos (250 x 10⁹/L) están altos y sugieren hemólisis, una causa conocida de anemia en el lupus: probable motivo de la anulación.',
    },
    {
      number: 138,
      kind: 'frontera',
      topicId: 'lupus',
      tag: 'Hematología · TTPA alargado',
      stem: 'Varón de 80 años con gonartrosis. Acude a estudio preoperatorio previo a prótesis de rodilla derecha. Su hemograma es normal. Los tests de coagulación muestran INR:1, tiempo de cefalina-caolín 47´´ (valor normal 27-37). La agregación plaquetaria con ristocetina está ligeramente alterada, pero es normal con colágeno y ADP. El paciente no refiere ninguna clínica hemorrágica. ¿Cuál es la causa de esta alteración en las pruebas de coagulación?',
      options: [
        'Heterocigosis para hemofilia A.',
        'Enfermedad de von Willebrand tipo I.',
        'Anticoagulante lúpico.',
        'Síndrome de Bernard-Soulier.',
      ],
      correct: 2,
      explanation:
        'TTPA alargado sin clínica hemorrágica y agregación con ristocetina algo alterada (normal con colágeno y ADP): von Willebrand tipo 1 leve. El anticoagulante lúpico alarga el TTPA pero no altera la agregación con ristocetina.',
    },
    {
      number: 42,
      kind: 'frontera',
      topicId: 'vasculitis',
      tag: 'Pediatría · Kawasaki',
      stem: '¿Cuál es una manifestación de la fase febril aguda de la enfermedad de Kawasaki?',
      options: [
        'Inyección ocular conjuntival bilateral no exudativa.',
        'Descamación de los dedos de las manos y los pies.',
        'Trombopenia menor de 100.000 plaquetas/mm3.',
        'Aparición de los aneurismas coronarios.',
      ],
      correct: 1,
      explanation:
        'En la fase aguda febril del Kawasaki aparece la inyección conjuntival bilateral no exudativa. La descamación de los dedos y los aneurismas coronarios son de la fase subaguda; la trombopenia no es típica (lo es la trombocitosis, también subaguda).',
    },
    {
      number: 15,
      kind: 'frontera',
      topicId: 'autoinflamatorias',
      tag: 'Nefrología · Amiloidosis',
      stem: 'Se muestra la biopsia (IMAGEN 15) de un paciente afecto de una enfermedad sistémica que puede afectar a múltiples órganos. En la exploración presta especial atención a la posible afectación neurológica. ¿Cuál de estos hallazgos le parece más probable en esta situación?',
      imageUrl: 'https://pub-a0af2de03fec4dd2b89a37964efd1716.r2.dev/questions/2026/15.png',
      options: [
        'Hipotensión ortostática sin respuesta cronotrópica adecuada.',
        'Nistagmo horizontal.',
        'Edema de papila.',
        'Debilidad muscular proximal sin alteraciones sensitivas.',
      ],
      correct: 1,
      explanation:
        'El glomérulo aparece ocupado por material eosinófilo, amorfo y acelular, compatible con amiloide (la confirmación exige rojo Congo con birrefringencia verde manzana, que la imagen no muestra). La amiloidosis, sobre todo la AL, puede dar neuropatía autonómica: hipotensión ortostática sin taquicardia compensadora.',
    },
    {
      number: 90,
      kind: 'frontera',
      topicId: 'espondiloartritis',
      tag: 'Trauma · Lumbalgia',
      stem: '¿Cuál de las siguientes es una red-flag durante la anamnesis y exploración física de una lumbalgia?',
      options: [
        'Dolor lumbar de patrón mecánico.',
        'Dolor a la palpación de espinosas.',
        'Antecedentes personales de proceso neoplásico.',
        'Paciente de 45 años.',
      ],
      correct: 3,
      explanation:
        'Bandera roja: antecedente de cáncer (sospecha de metástasis). También la edad avanzada o menor de 20 años, fiebre, pérdida de peso, dolor nocturno o déficit neurológico. El dolor inflamatorio en un joven orienta a espondiloartritis.',
    },
  ],
  sourcesNote:
    'Pesos calculados con el recuento de preguntas MIR de Reumatología de 2015 a 2025, agrupadas en 16 bloques temáticos propios, y con la clasificación de las preguntas del MIR 2026 (cuaderno oficial, versión 0). Las respuestas del MIR 2026 están contrastadas con las definitivas publicadas tras las impugnaciones; ninguna pregunta de Reumatología fue anulada (la 139, de anemia en el lupus, sí, pero es de Hematología). La previsión para el MIR 2027 es una media ponderada (70 % los últimos 5 MIR, 30 % los anteriores): orientativa, no una predicción exacta. La extensión de cada tema es aproximada.',
}
