import { create } from 'zustand'
import type { UIState } from '@/components/mapas/proto/types/store.types'

export const useUIStore = create<UIState>((set) => ({
  stylePanelOpen: false,
  multiSelect: false,
  exportOpen: false,
  setExportOpen: (exportOpen) => set({ exportOpen }),
  cameraLocked: false,
  setCameraLocked: (cameraLocked) => set({ cameraLocked }),
  focusBlur: true,
  setFocusBlur: (focusBlur) => set({ focusBlur }),
  setMultiSelect: (multiSelect) => set((s) => (s.multiSelect === multiSelect ? s : { multiSelect })),
  selectedNodeId: null,
  theme: 'light',
  bgStyle: 'dots-light',
  isDragging: false,
  physicsEnabled: true,
  categoryStyles: {},
  categoriesPanelOpen: false,
  searchOpen: false,
  setSearchOpen: (searchOpen) => set({ searchOpen }),
  setCategoryStyles: (categoryStyles) => set({ categoryStyles }),
  setCategoriesPanelOpen: (open) => set({ categoriesPanelOpen: open }),
  setPhysicsEnabled: (v) => set({ physicsEnabled: v }),
  setStylePanelOpen: (open) => set({ stylePanelOpen: open }),
  setSelectedNodeId: (id) => set({ selectedNodeId: id }),
  setTheme: (theme) => set({ theme }),
  setBgStyle: (bgStyle) => set({ bgStyle }),
  setDragging: (v) => set({ isDragging: v }),
}))
